Add LabVIEW file extensions and samples
github/linguist pull request #5035
Opened 2020-10-01 16:47 UTC by dillonledoux

## Description

I added the new extensions for LabVIEW code and added real world examples for said code. 

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - Samples used are shipped with LabVIEW itself so no URL exists
    - Sample license(s): http://ni.com/samplecodelicense - All code is free to be distributed and used without restriction
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

2020-10-02 09:34 UTC, lildude requested changes
As I mentioned in https://github.com/github/linguist/issues/5033, Linguist can not be used to classify binary files as they are _not_ code and thus not readable. Linguist doesn't even try to analyse them.

Please remove the binary files and the extensions from the list in `language.yml`.

We also only need one sample of each new extension that is a readable text file. Sometimes two samples are useful if they're significantly different but still representative of real-world usage. All of the files with identical extensions in this PR appear to be very similar so only one of each is needed.

Please also update the template to provide a link to each of the new extensions you're adding showing their popularity on GitHub.com.

2020-10-02 16:45 UTC, JT0407 approved these changes

2020-10-02 16:46 UTC, JT0407 approved these changes

2020-10-05 21:07 UTC, dillonledoux reviewed
I have removed the binary file references so now it should be good

2020-10-14 10:10 UTC, Alhadis approved these changes

2020-10-26 09:53 UTC, lildude approved these changes

2020-10-26 10:00 UTC, merged