Add devcontainer.json to JSONC
github/linguist pull request #5081
Opened 2020-11-04 00:41 UTC by Porges

This file is VS Code specific & allows comments: https://code.visualstudio.com/docs/remote/devcontainerjson-reference

## Description

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github-lightshow.herokuapp.com/
  - New: https://github-lightshow.herokuapp.com/

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2020-11-04 10:31 UTC, lildude requested changes
>  - [x] I have included a real-world usage sample for all extensions added in this PR:

Whoopsie. Looks like you forgot to commit the sample you've said you've added 😉  

The example you referenced looks to be in a repo covered by the MIT license, so feel free to add it to this PR and update the template to point to the original source and state the license.

2020-11-04 17:53 UTC, Porges commented
> > * [x]  I have included a real-world usage sample for all extensions added in this PR:
> 
> Whoopsie. Looks like you forgot to commit the sample you've said you've added 😉
> 
> The example you referenced looks to be in a repo covered by the MIT license, so feel free to add it to this PR and update the template to point to the original source and state the license.

Ah, I didn't realize that “included” meant to actually put it in the repo

2020-11-04 20:28 UTC, Porges commented
@lildude done!

2020-11-05 09:55 UTC, lildude approved these changes

2020-11-05 09:55 UTC, merged