Classifier cross-validation script and workflow
github/linguist pull request #5142
Opened 2021-01-14 21:30 UTC by smola

## Description
Added `script/cross-validation` to run leave-one-out cross-validation on the classifier. It will output a list of validated samples along with `GOOD` for successful samples and `BAD (<Language>)` for errors.

By the default it will check only samples with ambiguous filenames and without catch-all heuristics. This behavior can be disabled with the `--all` flag. Languages without, at least, 2 samples, are always ignored.

If the `--test` flag is used, the number of errors will be checked against a hardcoded threshold, and it will exit with 1 status if the number of errors is not less or equal than this threshold.

A new GitHub Actions job is added to run this on every push.

A small optimization was made to Classifier#train!. It speeds it up by ~5x. This will not be a big deal for most users, but it makes a big difference when doing cross-validation.

## Checklist:
_N/A_

2021-01-25 10:20 UTC, lildude requested changes
I like this addition and the fact we'll soon be testing the classifier.

Spotted one typo and offered a few style improvements.

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +  out.puts "The --test flag can be used to verify that the number of errors is acceptable."
Quoting consistency:

```suggestion
  out.puts ''
  out.puts 'Performs leave-one-out cross-validation of the classifier.'
  out.puts 'By default, outputs results only for samples with ambiguous extensions.'
  out.puts 'If the --all flag is given, all samples and languages are considered.'
  out.puts ''
  out.puts 'The --test flag can be used to verify that the number of errors is acceptable.'
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +    STDERR.puts ""
Quotes:

```suggestion
    STDERR.puts ''
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +    STDERR.puts "Invalid command line argument: ${arg}"
Whoopsie:

```suggestion
    STDERR.puts "Invalid command line argument: #{arg}"
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +  path = sample[:path].sub("#{Samples::ROOT}/", "")
Quotes:

```suggestion
  path = sample[:path].sub("#{Samples::ROOT}/", '')
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +  STDERR.puts ""
Quotes: 

```suggestion
  STDERR.puts ''
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +    STDERR.puts "WARNING: No cross-validation possible for #{sample[:language]} (only one sample)"
As this is just a warning, lets use `warn` instead:

```suggestion
    warn "WARNING: No cross-validation possible for #{sample[:language]} (only one sample)"
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +    STDERR.puts "Number of errors (#{total_errors}) is within the acceptable threshold (#{acceptable_errors})"
We probably don't want this on `STDERR` as this is a "success":

```suggestion
    STDOUT.puts "Number of errors (#{total_errors}) is within the acceptable threshold (#{acceptable_errors})"
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +  end
I think we can on-liner this guard:

```suggestion
  return nil if $skip_extensions.include? sample[:extname]
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +    end
Here too:

```suggestion
    return nil if languages.length == 1
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +    end
Here too:

```suggestion
    return nil if languages.length <= 1
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +  end
```suggestion
  total_errors += 1 if res.include? ' BAD '
```

2021-01-25 10:20 UTC, lildude commented on script/cross-validation
> +  end
```suggestion
  acceptable_errors = $all ? ACCEPTABLE_ERRORS_ALL : ACCEPTABLE_ERRORS
```

2021-01-25 21:42 UTC, smola commented on script/cross-validation
> +ACCEPTABLE_ERRORS = 61
```suggestion
ACCEPTABLE_ERRORS = 53
```

2021-01-27 09:43 UTC, lildude approved these changes
LGTM. Thanks for this. 😍

2021-01-27 09:43 UTC, merged