Add Beef language
github/linguist pull request #5190
Opened 2021-02-06 02:36 UTC by Nixinova

Adds the Beef language, extension `.bf`.

Implements #5066

Usage seems to check out: https://github.com/github/linguist/issues/5066#issuecomment-774380976

Color `#4BB4E3` averaged from background of https://beeflang.org

Use C# grammar as Beef is "most[ly] directly derived from C#" - https://github.com/beefytech/Beef

## ~Checklist
- [x] Added language
- [ ] Implemented heuristic
- [ ] Added samples
- [x] Added grammar (C#)

2021-02-06 02:44 UTC, Nixinova commented
Brainf— and HyPhy don't seem to be in `heuristics.yml` or `heuristics.rb`; how do I add the Beef heuristic, and how are the others disambiguated?

2021-02-06 03:24 UTC, Alhadis commented
> how do I add the Beef heuristic, and how are the others disambiguated?

Heuristics are optional. They're only necessary when our classifier does a poor job of telling two languages apart. Brainfuck's syntax is—to the surprise of absolutely nobody—easy to distinguish from HyPhy. Hence our classifier gets it right based off of our samples.

Usually, a heuristic matches a predictable and repetitive pattern, or syntax that's valid in one language but illegal in another. If neither is possible, it's best to avoid heuristics altogether and leave it to our classifier to figure it out.

2021-02-06 03:40 UTC, Alhadis requested changes

2021-02-06 03:40 UTC, Alhadis commented on lib/linguist/languages.yml
> +  color: "#4BB4E3"
> `#4BB4E3`

Come on, nobody likes a blue steak. 😉 We all know what the *real* colour should be:

# `#BEEEEF`

I'm kidding, of course. The colour should actually be `#a52f4e`: sampled from the centre of the [language's logo](https://www.beeflang.org/img/Beef256.png), where its most visually-prominent colour is.

2021-02-09 09:46 UTC, lildude commented
As you're planning to rely on the classifier to correctly identify Beef `.bf` files, can you please add at least one more sample. The new "Classifier cross-validation" test allows us to confirm the classifier behaviour, however it needs at least two samples:

From the test output:

```
WARNING: No cross-validation possible for Beef (only one sample)
```

2021-02-09 19:26 UTC, Nixinova commented
Added two more

2021-02-10 09:57 UTC, lildude commented
> Added two more

Thanks. Can you update the OP with links to the sources and their licenses too, and then I think we're good to go.

2021-02-10 20:21 UTC, Nixinova commented
Updated

2021-02-11 09:34 UTC, lildude approved these changes

2021-02-11 09:34 UTC, merged