Add CODEOWNERS file
github/linguist pull request #5254
Opened 2021-03-06 07:21 UTC by Nixinova

Resolve #5253

## Description

[CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) is a file used on GitHub "to define individuals or teams that are responsible for code in a repository." This repository even has one such file.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  [filename:codeowners](https://github.com/search?q=filename%3Acodeowners&type=code) - 126K results
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample: [CODEOWNERS](https://github.com/dotnet/samples/blob/master/.github/CODEOWNERS) licensed under [CCBY4.0](https://github.com/dotnet/samples/blob/master/LICENSE)
  
  - [x] I have included a syntax highlighting grammar: [preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fbmalehorn%2Fcodeowners-language%2Fblob%2Fmaster%2Fsyntaxes%2Fcodeowners.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fsamples%2Fblob%2Fmaster%2F.github%2FCODEOWNERS&code=)

2021-03-06 07:55 UTC, Nixinova commented
Failed test just says `license needs review: Unlicense`

2021-03-07 08:49 UTC, YashTotale commented
Thanks for the prompt response to my issue (#5253)! 👍

2021-03-12 08:06 UTC, Alhadis requested changes

2021-03-12 08:06 UTC, Alhadis commented on vendor/README.md
> +- **CODEOWNERS:** [bmalehorn/codeowners-language](https://github.com/bmalehorn/codeowners-language)
I hacked together a `CODEOWNERS` grammar in Alhadis/language-etc@fc2856e, which yields decidedly clearer output:
* [`Alhadis/language-etc`](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2FAlhadis%2Flanguage-etc%2Fblob%2Fmaster%2Fgrammars%2Fcodeowners.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-etc%2Fmaster%2Fsamples%2FCODEOWNERS&code=)
* [`bmalehorn/codeowners-language`](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fbmalehorn%2Fcodeowners-language%2Fblob%2Fmaster%2Fsyntaxes%2Fcodeowners.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FAlhadis%2Flanguage-etc%2Fmaster%2Fsamples%2FCODEOWNERS&code=)

Its highlighting is also consistent with that of `.gitignore` files, which it's modelled off of.

2021-03-12 21:44 UTC, Alhadis approved these changes

2021-03-19 08:24 UTC, lildude approved these changes

2021-03-19 08:24 UTC, merged