Add _redirects
github/linguist pull request #5262
Opened 2021-03-09 07:26 UTC by Nixinova

Resolve #5145

## Description

The _redirects file is used by [Netlify](https://netlify.com) for configuring redirects/rewrite rules.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Used in 6K+ repos ([query](https://github.com/search?p=2&q=path%3A%2F+filename%3A"_redirects"+-language%3ACSV&type=Code)).
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Custom sample
  
  - [x] I have included a syntax highlighting grammar: [preview](https://github-lightshow.herokuapp.com/?utf8=y&scope=from-url&grammar_url=https://github.com/Nixinova/tmLanguage/blob/main/grammars/_redirects.tmLanguage.yaml&code_source=from-url&code_url=https://github.com/Nixinova/tmLanguage/blob/main/samples/_redirects.txt)

2021-03-09 07:39 UTC, Nixinova commented
Not sure why the test is failing, the submodule was added fine in https://github.com/github/linguist/pull/5262/commits/765262469530ffd582bbeaf4e799edbe6784aab4.

2021-03-13 21:38 UTC, Alhadis requested changes

2021-03-13 21:38 UTC, Alhadis commented on grammars.yml
> +- text._redirects
**Nitpick:** This should be `source.`, not `text.`. The two scope-bases roughly correspond to the following language types:

`source.` ⇒ `data`, `programming`  
`text.` ⇒ `markup`, `prose`

I'd also rename `_redirects` to `redirects`. A good scope-name should match:

~~~regexp
/^(source|text)\.[a-z]+(-[a-z]+)*$/
~~~

So altogether:

```suggestion
- source.redirects
```

2021-03-13 21:38 UTC, Alhadis commented on lib/linguist/languages.yml
> +Netlify Redirects:
Hrm, perhaps we should name this `Redirect Rules` instead? The file-format looks very generic, and I imagine the syntax could be repurposed by other routers and web-servers (so omitting the obvious Netlify connection might encourage reuse).

`.gitignore` files were named _"Ignore List"_ for this very same reason—it enabled us to add several other mostly-identical formats in a clean, sane fashion.

2021-03-13 22:30 UTC, Alhadis approved these changes

2021-03-15 09:19 UTC, lildude approved these changes

2021-03-15 09:19 UTC, merged