Added B4X programming language
github/linguist pull request #5310
Opened 2021-04-05 12:12 UTC by AnywhereSoftware

Added B4X programmaing language

## Description
Add B4X programming language

## Checklist:

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      - https://github.com/search?q=extension%3Ab4j+sub&type=Code
      -  https://github.com/search?q=extension%3Ab4a+sub&type=Code
    b4r and b4i are more rare but they are unique to B4X.
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - A cross platform (B4A, B4J and B4i) project is included in the samples folder.
    - Sample license(s): MIT. If needed I can make it public domain. I wrote the sample.
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2021-04-06 06:54 UTC, lildude requested changes
Along with removing the low-usage extensions as commented inline, please remove all sample files from the PR that do not have the extensions you're adding support for.

2021-04-06 06:54 UTC, lildude commented on lib/linguist/languages.yml
> +  - ".b4r"
Please remove the extensions that you've stated don't meet the usage requirements

2021-04-06 08:18 UTC, lildude commented
Looks like the current usage on GitHub.com for both extensions proposed doesn't meet the minimum requirements for inclusion yet:

- `b4j`
   Total files found: 561
   Unique public user/repos: 52
   Unique owners: 30

- `b4a`
   Total files found: 355
   Unique public user/repos: 124
   Unique owners: 89

2021-09-17 16:30 UTC, pyhoon approved these changes

2021-09-17 16:32 UTC, pyhoon approved these changes

2023-02-17 10:09 UTC, lildude commented
Closing this as stale as it has been sitting without the requested changes being made for fast approaching two years. Usage is also nowhere near ready for inclusion.

Please open a new and complete PR when usage has met required levels.

2023-02-17 10:09 UTC, closed without merging