feat(grammar,languages): add support for CUE language
github/linguist pull request #5312
Opened 2021-04-06 23:00 UTC by zchee

This PR adds support for the [CUE language](https://cuelang.org).

## Description

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acue+package+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/cuelang/cue/blob/447606047bdd32f79029a4be5424af3a09ea15f2/doc/tutorial/kubernetes/quick/services/kube.cue
    - Sample license(s): [Apache-2.0 License](https://github.com/cuelang/cue/blob/master/LICENSE)
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fcue-sh%2Fvscode-cue%2Fblob%2F7bd21882dc0e5299271597f18f2740394714cfea%2Fsyntaxes%2Fcue.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fcuelang%2Fcue%2Fblob%2F447606047bdd32f79029a4be5424af3a09ea15f2%2Fdoc%2Ftutorial%2Fkubernetes%2Fquick%2Fservices%2Fkube.cue&code=
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

2021-04-06 23:01 UTC, zchee commented
/cc @mpvl @myitcv

2021-04-07 04:42 UTC, myitcv commented
@zchee wonderful!

Cross referencing https://github.com/github/linguist/issues/5013

@lildude any pointers/additional things we should consider as part of this PR?

2021-04-07 07:30 UTC, lildude commented
> @lildude any pointers/additional things we should consider as part of this PR?

Yes... https://github.com/github/linguist/issues/5013#issuecomment-804263183

2021-04-07 09:39 UTC, zchee commented
@lildude ah, What should I do? edit https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml ...?

2021-04-08 09:13 UTC, lildude commented
What we will need is for cue sheet to be added as part of this PR too so this PR will then implement the two most prominent languages that currently use the `.cue` extension on GitHub.

I don't think a heuristic will be needed as the two languages are quite distinct so the classifier should be able to differentiate between the two. Adding two good samples of each would certainly help.

So to put it into points of things to do in this PR:

- Add support for "Cue Sheet" as a new data language
- Add two cue sheet samples
- Add another CUE sample

2021-04-08 11:45 UTC, zchee commented
@lildude thanks for very details reply.
And I understand all, will do and mention to you after done.

2021-04-12 02:57 UTC, zchee commented
@lildude added Cue Sheet language support. PTAL.

2021-04-12 06:54 UTC, zchee commented
@lildude sorry, fixed CI error. PTAL again.

2021-04-13 08:44 UTC, lildude requested changes
Thanks for adding the Cue Sheet support.

Can you please rename it to use titlecase as I've commented inline. You'll need to rename the directory holding the samples too.

Can you please also update the template to link to the source of all four of the samples in this PR and state the license for each file.

🙇

2021-04-13 08:44 UTC, lildude commented on lib/linguist/languages.yml
> +Cue sheet:
Titlecase is preferred: 

```suggestion
Cue Sheet:
```

2021-04-13 08:44 UTC, lildude commented on vendor/README.md
> +- **Cue sheet:** [relikd/CUE-Sheet_sublime](https://github.com/relikd/CUE-Sheet_sublime)
As above.

```suggestion
- **Cue Sheet:** [relikd/CUE-Sheet_sublime](https://github.com/relikd/CUE-Sheet_sublime)
```

2021-04-15 04:02 UTC, zchee commented
@lildude thanks, will fix

2021-04-15 04:37 UTC, zchee commented
@lildude PTAL.

2021-04-16 09:38 UTC, lildude approved these changes
😍 Thanks @zchee.

You've just missed the last release so GitHub.com won't gain support until the next release is made which will be in about a month's time.

2021-04-16 10:11 UTC, merged

2021-04-16 10:48 UTC, zchee commented
@lildude Thanks a lot!