separated cython from python
github/linguist pull request #5462
Opened 2021-07-14 07:10 UTC by cvanelteren

Seperates cython from python as per discussion (https://github.com/github/linguist/issues/5443#issuecomment-879470114).

2021-07-19 09:30 UTC, lildude requested changes

2021-07-19 19:31 UTC, cvanelteren commented on lib/linguist/languages.yml
> +  color: "#fedf5b"
Done!

2021-07-19 20:52 UTC, Nixinova commented on lib/linguist/languages.yml
> +  color: "#fedf5b"
That should be put in the PR description instead of as a comment in the file

2021-07-20 05:06 UTC, cvanelteren commented on lib/linguist/languages.yml
> +  color: "#fedf5b"
Ah apologies, I misunderstood. It should be fixed now. Also put thread for more background.

2021-07-20 06:23 UTC, lildude requested changes
Thanks for adding the reason for the colour choice to the OP. You're also going to need to update the test by removing the line at https://github.com/github/linguist/blob/b980593f3fe2bdd1dacb00d918049a87ad9f8f73/test/test_language.rb#L99

2021-07-20 15:12 UTC, cvanelteren commented
> Thanks for adding the rain for the colour choice to the OP. You're also going to need to update the test by removing the line at
> 
> https://github.com/github/linguist/blob/b980593f3fe2bdd1dacb00d918049a87ad9f8f73/test/test_language.rb#L99

Done!

2021-07-21 05:06 UTC, lildude approved these changes
LGTM, thanks.

2021-07-21 05:15 UTC, merged