Adding Earthly language
github/linguist pull request #5613
Opened 2021-10-22 19:00 UTC by mccartney

## Description
Adding support for new language: Earthly which is a build automation tool.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=filename%3AEarthfile+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [github.com/earthly/earthly/blob/main/examples/java/Earthfile](https://github.com/earthly/earthly/blob/main/examples/java/Earthfile)
    - Sample license(s):
      - [MPL 2.0](https://github.com/earthly/earthly/issues/1292#issue-1024145945)  
  
  - [x] I have included a syntax highlighting grammar: [github-lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=json&grammar_url=https%3A%2F%2Fgithub.com%2Fearthly%2Fearthfile-grammar%2Fblob%2Fmain%2Fsyntaxes%2Fearthfile.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fearthly%2Fearthly%2Fblob%2Fmain%2Fexamples%2Fjava%2FEarthfile&code=)
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.
    - No, as the file name associated (Earthfile) is unique

2021-11-25 09:49 UTC, lildude requested changes

2021-11-25 09:49 UTC, lildude commented on lib/linguist/languages.yml
> +  - ".earthfile"
Please remove this... there doesn't appear to be a single `.earthfile` on GitHub so it's a very very long way from meeting our minimum usage requirement 😁

2021-11-25 09:56 UTC, mccartney commented on lib/linguist/languages.yml
> +  - ".earthfile"
```suggestion
```

2021-11-25 10:08 UTC, lildude requested changes
Oh yes, and we need the cached license file from the grammar.

2021-11-29 09:51 UTC, lildude approved these changes

2021-11-29 09:58 UTC, merged