Add GSC
github/linguist pull request #5634
Opened 2021-11-04 09:46 UTC by Jake-NotTheMuss

## Description

GSC is a programming language used for Call of Duty's virtual machine.
## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      - .gsc extension: https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Agsc+NOT+nothack
      - .csc extension https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acsc+client+NOT+nothack
      - .gsh extension: https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Agsh+define+NOT+nothack
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/Joshr520/ee_patch/blob/main/scripts/zm/array_override/array_override_common.gsc
    - Sample license(s):
      - https://github.com/Joshr520/ee_patch/blob/main/LICENSE
  
  - [x] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=xml&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2FJake-NotTheMuss%2FCoDT7-Sublime%2Fmaster%2Fother%2Fgsc.tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2FJoshr520%2Fee_patch%2Fmain%2Fscripts%2Fzm%2Farray_override%2Farray_override_common.gsc&code=
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

2021-12-08 11:24 UTC, lildude requested changes
You've only listed three sample files in the OP but have added more. Please update the OP to list where you've obtain _all_ of the sample files and their respective licenses.

2021-12-09 07:01 UTC, Jake-NotTheMuss commented
The other files are directly from the Black Ops 3 mod tools. I think it's GNU v3 but I'll install Black Ops 3 to make sure and update with the license for those files when I confirm.

2021-12-09 09:33 UTC, Jake-NotTheMuss commented
I've added the license for the other samples, but the syntax highlighting grammar that was given is provided in the mod tools, so I guess that means it's licensed under GPL 3, so I will create my own with an acceptable license.

2021-12-09 09:50 UTC, lildude commented
> I've added the license for the other samples, but the syntax highlighting grammar that was given is provided in the mod tools, so I guess that means it's licensed under GPL 3, so I will create my own with an acceptable license.

Thanks. Can you update the OP to point to the source of the files too, as you've done with the current three files.

As for the grammar, the one you've added - https://github.com/Jake-NotTheMuss/CoDT7-Sublime.git - is covered by the Unlicense License, which is fine.

I still need to check usage levels of all extensions meet our requirements.

2021-12-09 11:27 UTC, Jake-NotTheMuss commented
Those scripts aren't on the Internet. Should I create a repo and push those files to it? And the license of the sample files can be anything, right?

2021-12-10 02:02 UTC, Jake-NotTheMuss commented
The rest of the sample files and their license have been added.

2021-12-14 11:04 UTC, Jake-NotTheMuss commented
Should I add tests for each GSC extension to test/test_heuristics.rb?

2021-12-17 16:04 UTC, Jake-NotTheMuss commented
@lildude

2021-12-17 16:20 UTC, lildude commented
> Should I add tests for each GSC extension to test/test_heuristics.rb?

That's what the test failure is telling you 😉 

Or you can remove the heuristics if these extensions are unique to this language.

2021-12-18 03:13 UTC, Jake-NotTheMuss commented
@lildude I added the heuristic tests for each extension. These extensions are not associated with any other supported language on github, but they are there just be certain non-GSC .gsc files aren't counted.

2022-01-12 02:26 UTC, Jake-NotTheMuss commented
@lildude Do I need to run the tests again or is there something else I need to do first?

2022-01-24 23:19 UTC, Jake-NotTheMuss commented
@Alhadis

2022-02-08 17:48 UTC, lildude requested changes
This PR is probably close to being merged based on the new temp limits detailed in https://github.com/github/linguist/issues/5756 however these samples are quite massive.

2022-02-08 17:48 UTC, lildude commented on samples/GSC/array_shared.gsc
> +#using scripts\codescripts\struct;
This file is massive and I don't think it adds much more than the sample above. Please remove it.

2022-02-08 17:48 UTC, lildude commented on samples/GSC/scene_shared.csc
> +#using scripts\codescripts\struct;
Wow!! This file is huge and seems to nearly repeat similar segments of code. Are you able to replace this with a smaller representative sample with less apparent duplication?

2022-02-08 17:48 UTC, lildude commented on samples/GSC/shared.gsh
> +#define PLAYER_1 0
Are you able to find a smaller sample? This file is mostly filled with `define` lines which don't differ by very much syntactically.

2022-02-08 21:33 UTC, Jake-NotTheMuss commented
> This PR is probably close to being merged based on the new temp limits detailed in #5756 however these samples are quite massive.

Samples should be a good size now

2022-02-09 09:37 UTC, lildude commented
@Alhadis would you mind taking a quick look at the regexes in this PR when you've got a mo? 🙇

2022-02-10 02:40 UTC, Alhadis requested changes

2022-02-10 08:23 UTC, Jake-NotTheMuss commented
@lildude @Alhadis

2022-02-10 08:39 UTC, Alhadis approved these changes

2022-02-10 09:53 UTC, merged