Php submodule
github/linguist pull request #5677
Opened 2021-12-07 12:19 UTC by ondrejmirtes

## Description

Based on https://github.com/github/linguist/issues/5668 I updated the repo that's used for PHP highlighting.

These are the features I added:

* respect indented HEREDOC terminator (https://github.com/ondrejmirtes/php.tmbundle/commit/413f949cff30cff7ec7b10e52c29854e95019879), https://php.watch/versions/7.3/relaxed-heredoc-nowdoc
* allow uncaptured exceptions (https://github.com/ondrejmirtes/php.tmbundle/commit/fe03f52ab679b164f4d21ec7ef0d361f4eda14b9), https://php.watch/versions/8.0/catch-exception-type
* support native "mixed" type (https://github.com/ondrejmirtes/php.tmbundle/commit/53c788b038794f052dc6a828534313abbcdb0ecb), https://php.watch/versions/8.0/mixed-type
* add static return type (https://github.com/ondrejmirtes/php.tmbundle/commit/9fd9c8f19d3ca3eb090e7f2478911917dbbd9bb4), https://php.watch/versions/8.0/static-return-type
* recognize match control structure (https://github.com/ondrejmirtes/php.tmbundle/commit/caa18329d413b32389e36be3f04a5ed863f4486b), https://php.watch/versions/8.0/match-expression
* highlight nullsafe operator (https://github.com/ondrejmirtes/php.tmbundle/commit/c36b500f8ceeba78c716a1bff2f98d0e7405d3da), https://php.watch/versions/8.0/null-safe-operator
* support native "never" type (https://github.com/ondrejmirtes/php.tmbundle/commit/23a2daa896cbcdfc4b1973c58216c1c082f0cbcf), https://php.watch/versions/8.1/never-return-type
* Add support for enum (https://github.com/ondrejmirtes/php.tmbundle/commit/1b3170714572ef6b1e3e9ea4dafa132a87e344c8), https://php.watch/versions/8.1/enums
* Add support for object type (https://github.com/ondrejmirtes/php.tmbundle/commit/0ad399c592ed68d1cfe36eb3c9e87a2831a869c4), https://wiki.php.net/rfc/object-typehint

I tested these changes in the TextMate editor on macOS.

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  
  - [ ] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [x] **I am changing the source of a syntax highlighting grammar**
  
  - Old: https://github.com/textmate/php.tmbundle
  - New: https://github.com/ondrejmirtes/php.tmbundle

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2021-12-07 12:57 UTC, lildude requested changes
Looks like you didn't use the `add-grammar` script as [per the docs](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar) to switch out the grammars, or if you did you've forgotten to commit & push the updates to the grammars README and cached license files.

Please use that script to replace to grammars and or push the missing changed files.

Additionally, have you checked all the grammar changes correctly render on [Lightshow](https://github-lightshow.herokuapp.com/)? I ask because TextMate uses Oniguruma but GitHub uses PCRE and some of the Oniguruma syntax isn't 100% compatible.

2021-12-07 16:03 UTC, ondrejmirtes commented
Sorry, I haven't noticed that, I just thought that updating the submodule is sufficient.

I don't have much luck with the `add-grammar` script though, looks like it needs a specific local ruby setup and I'm not able to get it going.

This is the output I'm getting:

```
$ script/add-grammar --replace vendor/grammars/php.tmbundle https://github.com/ondrejmirtes/php.tmbundle
Checking Docker is installed and running
Deregistering submodule: vendor/grammars/php.tmbundle
Cleared directory 'vendor/grammars/php.tmbundle'
Submodule 'vendor/grammars/php.tmbundle' (https://github.com/textmate/php.tmbundle) unregistered for path 'vendor/grammars/php.tmbundle'
rm 'vendor/grammars/php.tmbundle'
Registering new submodule: https://github.com/ondrejmirtes/php.tmbundle.git
Reactivating local git directory for submodule 'vendor/grammars/php.tmbundle'
latest: Pulling from linguist/grammar-compiler
Digest: sha256:beea1cdeca326efc617bcf891584955e31f62cf3ec0947621454306452044dc0
Status: Image is up to date for linguist/grammar-compiler:latest
docker.io/linguist/grammar-compiler:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
6 warnings found when compiling new grammar 'repository `vendor/grammars/php.tmbundle` (from https://github.com/ondrejmirtes/php.tmbundle)':
OK! added grammar source 'vendor/grammars/php.tmbundle'
	new scope: text.html.php
- Missing include in grammar: `text.html.php` (in `Syntaxes/PHP.plist`) attempts to include `text.html.basic` but the scope cannot be found
- Missing include in grammar: `text.html.php` (in `Syntaxes/PHP.plist`) attempts to include `source.sql` but the scope cannot be found
- Missing include in grammar: `text.html.php` (in `Syntaxes/PHP.plist`) attempts to include `text.xml` but the scope cannot be found
- Missing include in grammar: `text.html.php` (in `Syntaxes/PHP.plist`) attempts to include `source.js` but the scope cannot be found
- Missing include in grammar: `text.html.php` (in `Syntaxes/PHP.plist`) attempts to include `source.json` but the scope cannot be found
- Missing include in grammar: `text.html.php` (in `Syntaxes/PHP.plist`) attempts to include `source.css` but the scope cannot be found

These warnings are not fatal, but may mean the syntax highlighting on GitHub.com may not be as expected.

Caching grammar license
bundler: command not found: licensed
Install missing gem executables with `bundle install`
```

Why I try to run `bundle install`:

```
$ bundle install
Ignoring ffi-1.11.1 because its extensions are not built. Try: gem pristine ffi --version 1.11.1
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.6
Using public_suffix 4.0.6
Using addressable 2.8.0
Using bundler 1.17.2
Using byebug 11.1.3
Fetching charlock_holmes 0.7.7
Installing charlock_holmes 0.7.7 with native extensions
Errno::EACCES: Permission denied @ rb_sysopen -
/Users/ondrej/Development/linguist/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes/common.h
An error occurred while installing charlock_holmes (0.7.7), and Bundler cannot continue.
Make sure that `gem install charlock_holmes -v '0.7.7' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-linguist was resolved to 7.17.0, which depends on
    charlock_holmes
```

With `sudo` I get some `C` compile errors looks like:

<details><summary>Output</summary>

```
$ sudo bundle install
Password:
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all
non-root users on this machine.
Ignoring ffi-1.11.1 because its extensions are not built. Try: gem pristine ffi --version 1.11.1
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.6
Using public_suffix 4.0.6
Using addressable 2.8.0
Using bundler 1.17.2
Using byebug 11.1.3
Fetching charlock_holmes 0.7.7
Installing charlock_holmes 0.7.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/ondrej/Development/linguist/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
-r ./siteconf20211207-46753-rajdlv.rb extconf.rb
checking for -licui18n... yes
checking for unicode/ucnv.h... yes
checking for -lz... yes
checking for -licuuc... yes
checking for -licudata... yes
creating Makefile

current directory: /Users/ondrej/Development/linguist/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
make "DESTDIR=" clean

current directory: /Users/ondrej/Development/linguist/vendor/bundle/ruby/2.6.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
make "DESTDIR="
compiling converter.c
compiling encoding_detector.c
encoding_detector.c:31:32: warning: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts
[-Wcompound-token-split-by-macro]
        rb_hash_aset(rb_match, ID2SYM(rb_intern("type")), ID2SYM(rb_intern("text")));
                                      ^~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:1826:23:
note: expanded from macro 'rb_intern'
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
                      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:413:29:
note: expanded from macro 'ID2SYM'
#define ID2SYM(x) RB_ID2SYM(x)
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:408:33:
note: expanded from macro 'RB_ID2SYM'
#define RB_ID2SYM(x) (rb_id2sym(x))
                                ^
encoding_detector.c:31:32: note: '{' token is here
        rb_hash_aset(rb_match, ID2SYM(rb_intern("type")), ID2SYM(rb_intern("text")));
                                      ^~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:1826:24:
note: expanded from macro 'rb_intern'
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:1811:5:
note: expanded from macro 'RUBY_CONST_ID_CACHE'
    {                                                   \
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:413:29:
note: expanded from macro 'ID2SYM'
#define ID2SYM(x) RB_ID2SYM(x)
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:408:33:
note: expanded from macro 'RB_ID2SYM'
#define RB_ID2SYM(x) (rb_id2sym(x))
                                ^
encoding_detector.c:31:32: warning: '}' and ')' tokens terminating statement expression appear in different macro expansion contexts
[-Wcompound-token-split-by-macro]
        rb_hash_aset(rb_match, ID2SYM(rb_intern("type")), ID2SYM(rb_intern("text")));
                                      ^~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/ruby.h:1826:24:
note: expanded from macro 'rb_intern'
        __extension__ (RUBY_CONST_ID_CACHE((ID), (str))) : \
                       ^~~~~~~ [...]

2021-12-07 16:17 UTC, ondrejmirtes commented
Here's a Lightshow example:

Before: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=text.html.php&grammar_format=auto&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=%3C%3Fphp%0D%0A%0D%0Aclass+Foo+implements+Bar%0D%0A%7B%0D%0A%7D%0D%0A%0D%0Aenum+Foo+implements+Bar%0D%0A%7B%0D%0A%7D
After: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fondrejmirtes%2Fphp.tmbundle%2Fmaster%2FSyntaxes%2FPHP.plist&grammar_text=&code_source=from-text&code_url=&code=%3C%3Fphp%0D%0A%0D%0Aclass+Foo+implements+Bar%0D%0A%7B%0D%0A%7D%0D%0A%0D%0Aenum+Foo+implements+Bar%0D%0A%7B%0D%0A%7D

2021-12-07 16:36 UTC, lildude commented
Ah, looks like you're hitting one of the many problems with the macOS-supplied version of Ruby, which is why we discourage its use in the first part of the [CONTRIBUTING.md](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#dependencies) file.

You'll find all your problems disappear if you use a Ruby installed via one of the other means.

2021-12-07 16:56 UTC, ondrejmirtes commented
Alright, I installed `ruby` and `gcc` through Homebrew and looks like I'm getting further. Now the script is running something in Docker and it's taking a long time. It's something from this image `linguist/grammar-compiler:latest` and the output is:

```
 376 / 382   98.43% 1ss

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%

 376 / 382   98.43%
```

Let's see if it finishes.

2021-12-07 17:17 UTC, ondrejmirtes commented
Should be fine now, thank you.

2021-12-08 06:30 UTC, ondrejmirtes commented
Build failed, so I updated `vendor/licenses/git_submodule/php.tmbundle.dep.yml`.

2021-12-08 11:08 UTC, lildude approved these changes
Thanks for taking on maintaining this grammar.

2021-12-08 11:08 UTC, merged

2021-12-08 11:15 UTC, ondrejmirtes commented
Awesome, thank you! 👏