Add Clarity, Rholang, and Vyper
github/linguist pull request #5749
Opened 2022-01-24 16:39 UTC by chiedo

## Description

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      - https://github.com/search?q=extension%3Aclar&type=Code
      - https://github.com/search?q=extension%3Avy&type=Code
      - https://github.com/search?q=extension%3Arho&type=Code
  - [x] I have included a real-world usage sample for all extensions added in this PR:
  - [x] I have included a syntax highlighting grammar
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2022-01-24 16:40 UTC, chiedo commented
Not sure what's expected here!

`I have updated the heuristics to distinguish my language from others using the same extension.`

But think I took care of everything else!

2022-01-24 17:03 UTC, lildude requested changes
A heuristic is only needed when there is a common extension that is shared between multiple languages, so if these are all unique, you don't need to worry about it.

Please replace all the "hello worlds" with real-world examples. These are used to train the classifier. Replace reference the source of the samples and their respective licenses in the OP too.

As for Clarity support... I've pointed out that the grammar you've selected is license under GPL. We can't ship this. That said, there's already a PR open for Clarity at https://github.com/github/linguist/pull/5665 so lets rely on that one and use this just for the other two languages.

2022-01-24 17:39 UTC, chiedo commented on lib/linguist/languages.yml
> +  language_id: 238948365
Hmmm.. Things didn't seem alphabetical but I just gave it a shot and added those new entries to the places that seemed correct!

2022-01-24 17:42 UTC, chiedo commented on vendor/licenses/git_submodule/clarity-lsp.dep.yml
> +                        GNU GENERAL PUBLIC LICENSE
I removed Clarity!

2022-01-24 17:46 UTC, chiedo commented on vendor/licenses/git_submodule/clarity-lsp.dep.yml
> +                        GNU GENERAL PUBLIC LICENSE
And added new examples. How does the PR and OP look now?

2022-02-03 18:34 UTC, davidhq commented
My repo which is already used for Solidity has Vyper syntax 
https://github.com/davidhq/SublimeEthereum/tree/linguist

2022-02-03 18:40 UTC, davidhq commented
hmm seems that `.vy` extension is already working?

<img width="797" alt="Screenshot 2022-02-03 at 19 39 39" src="https://user-images.githubusercontent.com/3899/152407665-d86b743d-9f29-47c2-a9b4-269bcda1ae7e.png">

2022-02-03 18:46 UTC, davidhq commented
Here was discussion in 2019: https://github.com/github/linguist/pull/4453

not sure what happened and if vyper was added shortly afterwards ?

It does seem to be working and syntax is visible on `.py` files, however it's not listed here https://github.com/github/linguist/tree/master/vendor, just in [grammars.yml](https://github.com/github/linguist/blob/master/grammars.yml#L122) as mentioned.

2022-02-03 18:51 UTC, davidhq commented
So it would be good to double check ... :)

I took a look at https://github.com/tintinweb/vscode-vyper/blob/master/syntaxes/vyper.tmLanguage.json .. and it actually doesn't have any vyper native stuff... it's just straight python syntax.

If there is clarification that my syntax is currently used for `.vy` files and will remain so, I can invest more time in bringing it to same quality as latest Solidity syntax in the same repo is (more or less perfect).

2022-02-03 19:52 UTC, chiedo commented
It looks like there's also a PR already for Clarity! https://github.com/github/linguist/pull/5665

Given that there's Vyper and Clarity are both already covered, I think I'll go ahead and close this!

2022-02-03 19:52 UTC, closed without merging

2022-02-03 20:52 UTC, davidhq commented
@chiedo this is still useful, isn't it?

https://github.com/github/linguist/pull/5749/commits/7b98773827b87f61fe3cb1ba3db3f955735aebfa#diff-9c337ec09ccaaa1374713aad9ba26cdc1308586a27cb309a883a0b19bde663d8R7229-R7236

because as of now Vyper does not have an entry in [lib/linguist/languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) ... I wonder how GitHub currently manages to apply Vyper syntax to `.vy` files?

<img width="680" alt="Screenshot 2022-02-03 at 21 51 58" src="https://user-images.githubusercontent.com/3899/152426724-325752e2-942c-4996-9e2e-458dcdff2098.png">

2022-02-03 20:53 UTC, chiedo commented
I think I may be out of my depths with how linguist works. 🤔 @lildude I'm going to defer to you.

2022-02-03 20:55 UTC, davidhq commented
@lildude tl/dr Vyper syntax seems to be working and the only thing that is making it work seems to be this line:

<img width="797" alt="Screenshot 2022-02-03 at 19 39 39" src="https://user-images.githubusercontent.com/3899/152427111-42f86e66-cd4a-4f12-b412-68ee87dd55e2.png">

Vyper does not have an entry in `lib/linguist/languages.yml` at the moment.

2022-02-03 21:06 UTC, Nixinova commented
> I wonder how GitHub currently manages to apply Vyper syntax to `.vy` files?

Syntax highlighting has been manually applied in that repo: see https://github.com/t4sk/vyper-by-example/blob/master/.gitattributes

2022-02-03 21:07 UTC, Nixinova commented
> this is still useful, isn't it?

So yes this PR is still useful for properly adding Vyper

2022-02-03 21:33 UTC, davidhq commented
> > I wonder how GitHub currently manages to apply Vyper syntax to `.vy` files?
> 
> Syntax highlighting has been manually applied in that repo: see https://github.com/t4sk/vyper-by-example/blob/master/.gitattributes

ok, this explains a lot, thank you

> > this is still useful, isn't it?
> 
> So yes this PR is still useful for properly adding Vyper

I also think so, but this should probably not be merged:

https://github.com/github/linguist/pull/5749/commits/7b98773827b87f61fe3cb1ba3db3f955735aebfa#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584R1128-R1130

just this part more or less I believe

<img width="366" alt="Screenshot 2022-02-03 at 21 52 25" src="https://user-images.githubusercontent.com/3899/152432336-6ca32100-84fc-499a-aab0-95634b22e92c.png">

Reference to my grammar which is not copied directly from Python is already here:
https://github.com/github/linguist/blob/master/grammars.yml#L122

not sure if anything else has to be added to connect `source.vyper` to the [new Vyper definition entry](https://github.com/github/linguist/pull/5749/commits/7b98773827b87f61fe3cb1ba3db3f955735aebfa#diff-9c337ec09ccaaa1374713aad9ba26cdc1308586a27cb309a883a0b19bde663d8R7229-R7236)

2022-02-03 21:39 UTC, davidhq commented
> not sure if anything else has to be added to connect `source.vyper` to the [new Vyper definition entry](https://github.com/github/linguist/pull/5749/commits/7b98773827b87f61fe3cb1ba3db3f955735aebfa#diff-9c337ec09ccaaa1374713aad9ba26cdc1308586a27cb309a883a0b19bde663d8R7229-R7236)

I think the answer to this is:

```yaml
Vyper:
  type: programming
  tm_scope: source.vyper
  color: "#46cf44"
  extensions:
  - ".vy"
  ace_mode: text
  language_id: 1055641948
```

so the `tm_scope: source.vyper` instead of `tm_scope: none`

I'm speaking to myself, I know that it was obvious to devs on linguist :}

2022-02-03 21:42 UTC, davidhq commented
And not sure about the best color (currently #46cf44) which is green:
<img width="23" alt="Screenshot 2022-02-03 at 22 41 18" src="https://user-images.githubusercontent.com/3899/152433677-263e2092-a372-46fe-b8f2-26564838fa08.png">

who usually chooses this?

Vyper has this logo:
![vyper](https://user-images.githubusercontent.com/3899/152433796-c621229e-4b0f-401f-ad28-b6810d5f4e48.svg)

2022-02-03 21:56 UTC, Nixinova commented
> I also think so, but this should probably not be merged: just this part more or less I believe

If you want Vyper to have its own syntax highlighting, than the other stuff should stay. If it's exactly the same syntax as Python, than the tm_scope can be changed to source.python & all the other stuff could be removed.

> And not sure about the best color (currently `#46cf44`) which is green: who usually chooses this?

The creator of the PR , with justification.
The [docs](https://vyper.readthedocs.io/en/latest/toctree.html) use blue `#2980b9` so maybe thats a better choice.

2022-02-03 21:56 UTC, Nixinova commented
(Also, is this PR still 3 additions like the title says it is, or is it just Vyper now? If so the title should be changed.)

2022-02-04 06:23 UTC, Alhadis commented
*Nota bene:* Ideally, this should've been submitted as three separate PRs, rather than a single monolithic PR.

2022-02-06 21:11 UTC, davidhq commented
Hi!

@chiedo is it a good idea to maybe close this one:

https://github.com/github/linguist/issues/5741

and rename this current issue to **Add Vyper** ?

also to close these two or add relevant comments?

https://github.com/github/linguist/issues/5740
https://github.com/github/linguist/issues/5739

this would separate concerns as @Alhadis is suggesting.

then if anyone needs any of my further input on Vyper, I'm available... you can use my repo https://github.com/davidhq/SublimeEthereum/tree/linguist for this (it already has an entry in `grammars.yml` plus it's already used for Solidity) and if you plan to do it, I can invest more time into improving / double checking the quality of highlighter until next linguist release and additionaly for one after this after highlighter is observed in live environment.

2022-02-07 13:36 UTC, chiedo commented
@davidhq feel free to take this and run with it! Through this PR, I've realized I don't have a strong enough understanding of Linguist.

So y'all can take it from here!

I'll close my issues also. Feel free to reference them in any new issues or PRs.

2022-02-07 20:23 UTC, davidhq commented
@chiedo can you reopen this issue then and change it's name to **Add vyper**.

Then we wait for others to take it from here, I can't do much until vyper syntax from my repo is accepted, so I'll wait for that first.

2022-02-07 20:26 UTC, chiedo commented
Done @davidhq!

2022-02-08 04:45 UTC, davidhq commented
@chiedo tnx

@lildude and others, if I can help with preparing a PR based on info here and take a second look at vyper grammar inside my repo etc., let me know... this is provided that Vyper has now reached enough usage to merit inclusion... so if you provide input / opinion whenever suitable, it would be useful... thank you

2022-02-09 23:02 UTC, chiedo commented
Thanks for your work!