Add Monkey C language
github/linguist pull request #5776
Opened 2022-02-10 23:28 UTC by Nixinova

- Resolve #5563

## Description

Adds the [MonkeyC](https://developer.garmin.com/connect-iq/monkey-c/) language.

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      -  [6K+](https://github.com/search?q=extension%3Amc+using+toybox) with exact keywords ("using Toybox", the stdlib)
      - [16K+](https://github.com/search?q=extension%3Amc+using) with just "using"
      - [58K](https://github.com/search?q=extension%3Amc) overall
  - [x] I have included a real-world usage sample for all extensions added in this PR:
     - [Sample](https://github.com/uschi2000/garmin-max-speed/blob/develop/source/StartTimer.mc) under [Apache2](https://github.com/uschi2000/garmin-max-speed/blob/develop/LICENSE)
  
  - [x] I have included a syntax highlighting grammar:
    - [Source](https://github.com/ghisguth/vscode-monkey-c)
    - [Preview](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fghisguth%2Fvscode-monkey-c%2Fblob%2Fmaster%2Fsyntaxes%2Fmonkeyc.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fuschi2000%2Fgarmin-max-speed%2Fblob%2Fdevelop%2Fsource%2FStartTimer.mc&code=)

2022-02-14 10:47 UTC, lildude commented on lib/linguist/languages.yml
> +  - ".mc"
There appear to be a lot of other users of the `.mc` extension that don't all appear to be Monkey C and Linguist doesn't know about this extension yet, so they're all going to be classified as Monkey C. I think we're going to need to identify the language of at least one other user of this extension and add it, possibly with a heuristic too.

2022-02-15 03:34 UTC, Nixinova commented
Other stuff with `.mc`:
- [14K](https://github.com/search?q=extension%3Amc+%22MessageId%22&type=code) of [th](https://github.com/dotnet/aspnetcore/blob/fdbe28e9c3e6e5ff3f12a9ac75e6f4efc5bd82cc/src/Servers/IIS/AspNetCoreModuleV2/CommonLib/aspnetcore_msg.mc)[is](https://github.com/google/grr/blob/7c9ac0c9cc793cdd696a612ccad938ccf57baa02/grr/client/grr_response_client/nanny/GRRNanny.mc) translation file thing
- [8K](https://github.com/search?q=extension%3Amc+%22divert%22&type=code)/[9K](https://github.com/search?q=extension%3Amc+%22dnl%22&type=code) for some [mail thing](https://github.com/ulli-kroll/gentoo-arm64/blob/042c2f870527892d8053803cfd73741ded76da05/mail-mta/sendmail/files/sendmail-procmail.mc)
- [3K](https://github.com/search?q=extension%3Amc+%22oracle%22&type=code) of something Oracle-related
- [25K](https://github.com/search?q=extension%3Amc+-MessageId+-toybox+-divert+-oracle&type=code) other

2022-02-23 01:45 UTC, Nixinova commented
Should be good now.
The 3K "&copy; Oracle" files seem to be assembly but look like they are all inside a `jdk-*` folder.
I can't find any other common languages in the other 25K results.

2022-03-10 18:21 UTC, Alhadis requested changes
Just a few nits picked up during cursory review.

2022-03-10 18:21 UTC, Alhadis commented on lib/linguist/heuristics.yml
> +    pattern: '(?i)MessageId=|^;'
I'd restrict this pattern so `MessageId=` only matches at the beginning of lines (possibly with `/*` sandwiched in-between):

```suggestion
    pattern: '(?i)^[ \t]*(?>\/\*\s*)?MessageId=|^;'
```

As for the `^;` pattern… recalling that M4 is a language-agnostic templating engine, it's possible that `;` might match in less common scenarios (say, when generating the source of a configuration file). I'd therefore match `M4`'s heuristic first, before `Win32 Message Files`. See below.

2022-03-10 18:21 UTC, Alhadis commented on lib/linguist/heuristics.yml
> +    pattern: '^dnl|^divert\(|^\w+\(`'
```suggestion
    pattern: '^dnl|^divert\((?:-?\d+)?\)|^\w+\(`[^\n]*?'[),]'
```

1. IIRC, M4's [`divert()` built-in](https://web.mit.edu/gnu/doc/html/m4_9.html#SEC45) only accepts a numeric argument.

2. Traditional implementations of M4 use [\`old-school typewriter quotes'](https://github.com/Alhadis/Atom-XTermQuotes) for delimiting macro arguments.

2022-03-10 18:21 UTC, Alhadis commented on lib/linguist/heuristics.yml
> +    pattern: '\b(?:using|module|function|class|var)\b\s+\w'
The second `\b` is redundant, since `\s+` is already a word boundary.

2022-03-10 20:10 UTC, Nixinova commented
The syntax error was added in the second edit but for some reason the first edit failed as well. Whats up with that.

2022-03-10 20:24 UTC, Alhadis approved these changes

2022-03-10 20:25 UTC, Alhadis commented on lib/linguist/heuristics.yml
> +    pattern: '^dnl|^divert\((?:-?\d+)?\)|^\w+\(`[^\n]*?''[),]'
I swear I can never remember what YAML's frikkin' syntax is for escaping single-quotes… 🤦‍♂️

2022-03-24 11:49 UTC, lildude approved these changes

2022-03-24 12:00 UTC, merged