Added suport for Talon files
github/linguist pull request #5810
Opened 2022-02-28 21:31 UTC by Nova38

## Description

This pull request is adding support for Talon language. It is a scripting language that is used by [Talon](https://talonvoice.com/) to define and map voice commands to actions it can take. Talon is a hands-free input system for Windows, MacOS, and Linux. 
## Checklist:

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Atalon
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/knausj85/knausj_talon/blob/14a370f18f248ba19177a2543c49335b415a1464/text/line_commands.talon
      - https://talonvoice.com/docs/index.html#document-talon_files
    - Sample license(s):
      - Both are distributed under a MIT license
        - For the example from talonvoice.com license was clarified in their slack with the owner of the project (https://talonvoice.slack.com/archives/C9MHQ4AGP/p1646080894130499)
  
  - [X] I have included a syntax highlighting grammar: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fmrob95%2Fvscode-TalonScript%2Fblob%2Fmaster%2Fsyntaxes%2Ftalon.tmLanguage.yml&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fmrob95%2Fvscode-TalonScript%2Fblob%2Fmaster%2Fsyntaxes%2Ftalon.tmLanguage.yml&code=%23+activate+this+.talon+file+if+the+current+app+name+is+%22Chrome%22%0D%0A%23+you+can+find+app+names+by+running+ui.apps%28%29+in+the+REPL%0D%0Aapp.name%3A+Chrome%0D%0A-%0D%0A%23+key_wait+increases+the+delay+when+pressing+keys+%28milliseconds%29%0D%0A%23+this+is+useful+if+an+app+seems+to+jumble+or+drop+keys%0D%0Asettings%28%29%3A%0D%0A++++key_wait+%3D+4.0%0D%0A%0D%0A%23+activate+the+global+tag+%22browser%22%0D%0Atag%28%29%3A+browser%0D%0A%0D%0A%23+define+some+voice+commands%0D%0Ahello+chrome%3A+%22hello+world%22%0D%0Aswitch+tab%3A+key%28ctrl-tab%29%0D%0Ago+to+google%3A%0D%0A++++key%28ctrl-t%29+%23+note%3A+use+cmd-t+on+Mac%0D%0A++++insert%28%22google.com%22%29%0D%0A++++key%28enter%29
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

2022-03-24 05:19 UTC, Nova38 commented
Just wanted to check in and see if there is anything else i need to add to this pull request?

Thanks

2022-03-24 11:55 UTC, lildude requested changes

2022-03-25 03:20 UTC, Nova38 commented on samples/Talon/example.talon
> +    key(enter)
Okay, sorry about that. How many samples is ideal to include? (The line_commands file included in the pull request is one real world example, I have others real world examples I can add, but don't won't to overdue it)

2022-03-28 09:19 UTC, lildude commented on samples/Talon/example.talon
> +    key(enter)
One or two should be fine. Two would be best as it'll add a bit more data for the classifier to work with in the event another language is added with the same extension.

2022-03-28 10:56 UTC, Nova38 commented on samples/Talon/example.talon
> +    key(enter)
Sounds good. I went ahead and added two more samples to the pull request and added the links to the initial pull checklist. I as well removed the "hello world" samples info from the checklist.

2022-03-29 08:40 UTC, lildude commented on lib/linguist/languages.yml
> +  color: "#333333"
Do you really want this grey colour `#333333`?

2022-03-29 08:41 UTC, lildude requested changes
I've removed the HTML file you accidentally added and added a comment about the colour.

Please can you address the merge conflicts too.

2022-03-31 17:04 UTC, Nova38 reviewed
I Believe everything should be in-order now

2022-03-31 17:23 UTC, merged