Add Yul smart contract langauge (intermediate language for Ethereum V…
github/linguist pull request #5861
Opened 2022-04-15 19:31 UTC by davidhq

…irtual Machine)

Adding Yul --

Yul is a programming language that is being used as an intermediate language in the compilation of Ethereum smart contracts written in in the Solidity language. However, Yul is designed to be more general than Solidity, and may find additional uses soon. Source: https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/YUL____YUL?path=3463/32691/2451/9091

Yul is becoming more and more important, here is next week's solidity summit agenda:
https://summit.soliditylang.org/agenda.html

There is quite a lot of .yul code on GitHub already.

## Description

## Checklist:

- [] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]      
    - Sample license(s):    
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [X] **I am adding a new language.**
  - [X] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Ayul+NOT+nothack
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Ayulp+NOT+nothack
  - [X] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
      - https://docs.soliditylang.org/en/latest/yul.html
    - Sample license(s):
    - https://github.com/ethereum/solidity/blob/develop/LICENSE.txt
  - [X] I have included a syntax highlighting grammar: https://github.com/davidhq/SublimeEthereum
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2022-04-22 15:08 UTC, lildude requested changes
Please remove the `.yulp` extension.

Please also update the OP to link to the direct source of the two samples and state their respective licenses.

2022-04-22 15:08 UTC, lildude commented on lib/linguist/languages.yml
> +  - ".yulp"
There are only 52 `.yulp` files so nowhere near enough.

```suggestion
```

2022-04-25 07:59 UTC, davidhq commented
> Please remove the `.yulp` extension.
> 

done

> Please also update the OP to link to the direct source of the two samples and state their respective licenses.

Added direct links to samples, entire license is not present, all I could include is "© Copyright 2016-2021, Ethereum." visible at the bottom of the page.

If license for samples in longer form is needed I can write the team and ask if they can provide this? Please let me know if needed. Thank you

2022-04-26 08:44 UTC, lildude commented
> If license for samples in longer form is needed I can write the team and ask if they can provide this? Please let me know if needed. Thank you

This is fine, thanks. I've found from the source that the docs are in a repo covered by the GPL 3.0 so I've updated your OP with that.

2022-04-26 09:27 UTC, lildude approved these changes

2022-04-26 09:27 UTC, merged

2022-04-26 09:59 UTC, davidhq commented
> > If license for samples in longer form is needed I can write the team and ask if they can provide this? Please let me know if needed. Thank you
> 
> This is fine, thanks. I've found from the source that the docs are in a repo covered by the GPL 3.0 so I've updated your OP with that.

great, thank you!