Add Adblock language
github/linguist pull request #5968
Opened 2022-07-10 17:35 UTC by scripthunter7

## Description

Adds [Adblock](https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters) language with the `.adblock` extension.

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - **Please note that `.adblock` extension is rarely used (lists usually have `.txt` extension).** However, the syntax is used by many repositories:
      <details>
        <summary>Show repositories (243)</summary>
        
        https://github.com/51114u9/bolivia-ublockfilters
        https://github.com/abp-filters/abp-filters-anti-cv
        https://github.com/abp-filters/abp-filters-compliance
        https://github.com/abp-filters/abp-filters-hotfix
        https://github.com/abp-filters/abp-filters-mobile
        https://github.com/ABPindo/indonesianadblockrules
        https://github.com/abpvn/abpvn
        https://github.com/acnapyx/paywall-remover
        https://github.com/adblock-thai/thai-ads-filter
        https://github.com/adbyby/xwhyc-rules
        https://github.com/AdguardTeam/AdguardFilters (1.6K stars)
        https://github.com/AdguardTeam/AdGuardSDNSFilter
        https://github.com/AdguardTeam/FiltersRegistry
        https://github.com/akopachov/uBlock-AK-filter-rules
        https://github.com/andromedarabbit/List-KR
        https://github.com/anudeepND/blacklist
        https://github.com/anudeepND/youtubeadsblacklist
        https://github.com/AnXh3L0/blocklist
        https://github.com/anyuzu99/nothingblock
        https://github.com/arapurayil/aBL
        https://github.com/arichr/bakadvert
        https://github.com/austinhuang0131/0131-block-list
        https://github.com/Ayesh/Adblock-Sinhala
        https://github.com/B-Con/mute
        https://github.com/balupton/filters
        https://github.com/banbendalao/ADgk
        https://github.com/betterwebleon/international-list
        https://github.com/betterwebleon/slovenian-list
        https://github.com/bkazez/distractionblock
        https://github.com/BlackJack8/iOSAdblockList
        https://github.com/blocklistproject/Lists
        https://github.com/blogmangit/Cosmetic-Filters
        https://github.com/bmyjacks/adlists
        https://github.com/BPower0036/AdBlockFilters
        https://github.com/brave/adblock-lists
        https://github.com/brawdevtest/ioG-list
        https://github.com/brunomiguel/antinonio
        https://github.com/byaka/ublock-antiskimming-list
        https://github.com/caffeinewriter/DontPushMe
        https://github.com/catsxp/adblock-lists
        https://github.com/Cinnamon-Unltd/Anti-Kpop-Spammers-Filterlist-for-Twitter
        https://github.com/Circu1T-Bre4keR/My-rules-for-UMATRIX-and-UBLOCK-ORIGIN
        https://github.com/cjx82630/cjxlist
        https://github.com/ColumWalsh/unsullied
        https://github.com/cpeterso/clickbait-blocklist
        https://github.com/crazy-max/WindowsSpyBlocker
        https://github.com/Crystal-RainSlide/AdditionalFiltersCN
        https://github.com/cxw620/AdGuard-Rules
        https://github.com/Cybo1927/Hosts
        https://github.com/dagoll/filters-list
        https://github.com/DandelionSprout/adfilt
        https://github.com/DandelionSprout/adguard
        https://github.com/DandelionSprout/Swedish-List-for-Adblock-Plus
        https://github.com/danielnixon/no-comment
        https://github.com/DariusIurca/ROADBLK-EXTRA
        https://github.com/DavidYaacov/adblock_youtube_paid
        https://github.com/DeepSpaceHarbor/Macedonian-adBlock-Filters
        https://github.com/deletescape/noads
        https://github.com/dhowe/uAssets
        https://github.com/DoingDog/XXKiller
        https://github.com/dorjmi/nothingblock
        https://github.com/durablenapkin/scamblocklist
        https://github.com/duskwuff/syndicationblock
        https://github.com/EasyDutch-uBO/EasyDutch
        https://github.com/EasyList-Lithuania/easylist_lithuania
        https://github.com/easylist-thailand/easylist-thailand
        https://github.com/easylist/antiadblockfilters
        https://github.com/easylist/easylist (1.2K stars)
        https://github.com/easylist/easylistchina
        https://github.com/easylist/easylistdutch
        https://github.com/easylist/easylistgermany
        https://github.com/easylist/EasyListHebrew
        https://github.com/easylist/easylistitaly
        https://github.com/easylist/easylistportuguese
        https://github.com/easylist/easylistspanish
        https://github.com/easylist/KoreanList
        https://github.com/easylist/listear
        https://github.com/easylist/listefr
        https://github.com/easylist/ruadlist
        https://github.com/eEIi0A5L/adblock_filter
        https://github.com/eladkarako/hosts
        https://github.com/elypter/filter_processor
        https://github.com/elypter/generic_annoying_stickybar_filter
        https://github.com/emilstahl/blocklist
        https://github.com/endolith/clickbait
        https://github.com/evenxzero/Raajje-AdList
        https://github.com/examplecode/ad-rules-for-xbrowser
        https://github.com/farrokhi/adblock-iran
        https://github.com/festum/anti-bias-media
        https://github.com/FiltersHeroes/KAD
        https://github.com/FiltersHeroes/KADhosts
        https://github.com/FiltersHeroes/PolishAnnoyanceFilters
        https://github.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement
        https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev
        https://github.com/finnish-easylist-addition/finnish-easylist-addition
        https://github.com/francis-zhao/quarklist
        https://github.com/ftpmorph/ftprivacy
        https://github.com/FutaGuard/FutaFilter
        https://github.com/gfmaster/adblock-korea-contrib
        https://github.com/gioxx/xfiles
        https://github.com/gwarser/filter-lists
        https://github.com/Hackl0us/AdBlock-Rules-Mirror
        https://github.com/Hakame-kun/uBlock-Filters-Indonesia
        https://github.com/hant0508/uBlock-filters
        https://github.com/hawkeye116477/FilterListsDarkMode
        https://github.com/haykam821/Blocklists
        https://github.com/hdd1013/AdBlockListSubKr
        https://github.com/hirorpt/filters
        https://github.com/hit3shjain/Andromeda-ublock-list
        https://github.com/hl2guide/All-in-One-Customized-Adblock-List
        https://github.com/hl2guide/Filterlist-for-AdGuard-or-PiHole
        https://github.com/hoshsadiq/adblock-nocoin-list (1.3K stars)
        https://github.com/hoshsadiq/blocked-hosts
        https://github.com/Hubird-au/Adversity
        https://github.com/hufilter/hufilter
        https://github.com/hufilter/hufilter-dev
        https://github.com/Hunter-Github/the-best-stack-overflow
        https://github.com/HuzunluArtemis/TurkishAdblockList
        https://github.com/hXR16F/uBlock-Origin-Lists
        https://github.com/iam-py-test/my_filters_001
        https://github.com/iamashley0/topgg-ublock-filter
        https://github.com/IDKwhattoputhere/uBlock-Filters-Plus
        https://github.com/JanJastrow/blocked_domains
        https://github.com/jasonbarone/membership-app-block-list
        https://github.com/jbara2002/Melody-_Host
        https://github.com/jiayiming/jCleanList
        https://github.com/JohnyP36/Personal-List
        https://github.com/jwinnie/acceptable-ads
        https://github.com/k2jp/abp-japanese-filters
        https://github.com/K-mikaZ/new_approach_adb__1st
        https://github.com/kano1/I
        https://github.com/kano1/Kano
        https://github.com/kargig/greek-adblockplus-filter
        https://github.com/Karmesinrot/Anifiltrs
        https://github.com/kbinani/adblock-wikipedia
        https://github.com/kbinani/adblock-youtube-ads
        https://github.com/KCaglarCoskun/enur-filter-list
        https://github.com/Kees1958/WS3_annual_most_used_survey_blocklist
        https://github.com/kowith337/PersonalFilterListCollection
        h [...]

2022-07-11 00:37 UTC, Nixinova commented on lib/linguist/languages.yml
> +  type: markup
```suggestion
  type: data
```
`markup` refers to languages like HTML. The type should be `data` if it's just a text list of rules.

2022-07-12 10:29 UTC, lildude commented
> Please note that .adblock extension is rarely used. 

Yes, this means we can't add support for this extension.

> Filter lists usually have .txt extension (maybe [.txt heuristics required?](https://github.com/github/linguist/blob/212946f47cd7a2505a71bd82f65b1263a6b64395/lib/linguist/heuristics.yml#L647)).

This would probably be the best option, but you'll need to be quite careful with the heuristic to be sure you don't catch legit text files.

2022-07-13 08:03 UTC, lildude requested changes
See my previous comment https://github.com/github/linguist/pull/5968#issuecomment-1181593752 and @Nixinova's about the type.

2022-07-13 09:37 UTC, scripthunter7 commented
@lildude 
Thanks for the feedback! I'm still working on the regex. You can view the current state here: https://rubular.com/r/Q7XJYCSEzIi0Jk

I hope this length is still acceptable. I try to completely exclude false positive cases. If necessary, I can also provide a detailed explanation of some parts of the regular expression.

2022-07-13 12:13 UTC, Alhadis requested changes

2022-07-13 12:15 UTC, Alhadis commented
I've been tempted to add support for AdBlock filters in the past. I decided against it for two reasons:

1.	We're disambiguating against freeform text, which should be assumed to contain anything and everything; including examples of AdBlock filters in lengthier prose (think `README.txt`).

2.	An accurate heuristic will have abysmal performance. Consider rules as complex [as these](https://github.com/uBlockOrigin/uAssets/blob/4cde8e6edc35379b4fea440219db7bb560d554d1/filters/filters.txt#L162-L166):
	~~~
	about-drinks.com,familie.de,formel1.de,freenet.de,hifi-forum.de,kicker.de,…transfermarkt.*##+js(nostif, .call(null), 10)
	*.jpg$script,domain=allthingsvegas.com|aupetitparieur.com|bestfunnyjokes4u.com|cheatsheet.com|clashdaily.com|craigjames.com|designbump.com|grammarist.com|madworldnews.com|menrec.com|politicalcowboy.com|reviveusa.com|sonsoflibertymedia.com|thedesigninspiration.com|themattwalshblog.com|videogamesblogger.com
	~~~
	Not only do we need to validate variable-length lists of domains and CSS selectors, we also have to run this validation against _every_ single `.txt` file on GitHub. In pathological cases, this can have a noticeable impact on performance.

Hopefully these reasons double as a PSA for any aspiring language-designers to avoid using the `.txt` extension for their new file-formats. 😉

2022-07-13 12:47 UTC, scripthunter7 commented
> We're disambiguating against freeform text, which should be assumed to contain anything and everything; including examples of AdBlock filters in lengthier prose (think README.txt).

I don't know how many files this issue can affect. I assume this number is very low.

> An accurate heuristic will have abysmal performance. Consider rules as complex [as these](https://github.com/uBlockOrigin/uAssets/blob/4cde8e6edc35379b4fea440219db7bb560d554d1/filters/filters.txt#L162-L166)

Currently I only validate "obvious" parts, like `##^script` / `##+js(` and I think the chance that legit txt files do contain such data is quite low. See https://rubular.com/r/7vMkdzGVsqu8dV

> Not only do we need to validate variable-length lists of domains and CSS selectors, we also have to run this validation against every single .txt file on GitHub.

> Hopefully these reasons double as a PSA for any aspiring language-designers to avoid using the .txt extension for their new file-formats. 😉

That's why I didn't want to approach it from the side of heuristics in the first round, but the .adblock extension is rarely used :confused: My other idea was the manual override, see my first comment on this topic: https://github.com/ameshkov/VscodeAdblockSyntax/issues/48#issue-1269148703
It can also be an option that only the very clear things are included in the regex, e.g. header metadata, and in the remaining cases a manual override must be added to some repositories. Overall, the language is in active use on GitHub. What do you think would be a good solution?

2022-07-13 13:14 UTC, scripthunter7 commented
> Heuristics are only used when Linguist is classifying a file whose extension is shared by two or more languages.

Oh, I think we misunderstood each other :) I just mentoined the .adblock extension because it could create a "new standard" in the future (because of syntax highlight) and in this case we don't need to apply complex heuristics for all txt files. But since the extension is rarely used, it cannot be included here.  Stalemate 😕

Considering these facts, only the heuristic remains, but it still needs to be developed further in order to function as accurately and optimally as possible.

2022-07-13 14:05 UTC, scripthunter7 commented
I made the requested changes.

2022-07-28 15:06 UTC, scripthunter7 commented
@lildude @Alhadis 

I have a slightly different idea in order to solve this situation. It is enough to examine only the beginning of the txt files. Thus, false positive detection is completely excluded, and there will be no problems with the performance either.

There are two main cases where we can say that a file uses adblock syntax:
- It starts with `[{{ADBLOCKER_NAME}}]` or `[{{ADBLOCKER_NAME}} {{VERSION}}]`
  - Example: `[Adblock Plus 2.0]`, `[Adblock Plus 2.5.5]`, `[uBlock Origin 1.0.0.0]`, `[AdGuard 1.0]`
  - Combination: `[Adblock Plus 2.0; AdGuard 1.0]`
  - As a comment: `! [uBlock Origin]` (! or # are optional)
- The comments at the beginning of the file contains metadata
  - Possible metadata fields: `Title`, `Expires`, `Homepage`, `License`, `Version`, `Last modified`, `Time updated`
  - Example:
     ```
     ! Version: 202207281320
     ! Title: EasyList
     ! Last modified: 28 Jul 2022 13:20 UTC
     ! Expires: 4 days (update frequency)
     ! Homepage: https://easylist.to/
     ! Licence: https://easylist.to/pages/licence.html
     ```
     or (# is also comment / not all fields are always present)
     ```
     # Version: 202207281320
     # Title: EasyList
     ```
     or (empty lines or another comments allowed)
     ```
     ! ------------------------------

     ! Version: 202207281320
     ! Title: EasyList


     ```

I've collected the required 200 unique repositories that contain such files:

<details>
<summary>Show links (205)</summary>


https://github.com/0ld/adblock-plus-2ch-ban/blob/master/ban.txt
https://github.com/02030pllolipop/Rules-after-famlam-redundantRuleChecker/blob/master/Big_mixtures_%26_breakdowns/A2.txt
https://github.com/abpvn/abpvn/blob/master/filter/abpvn.txt
https://github.com/acnapyx/paywall-remover/blob/master/paywall-remover-anon.txt
https://github.com/adblockplus/python-abp/blob/master/tests/data/filterlist.txt
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_112_ListeAR/filter.txt
https://github.com/andromedarabbit/List-KR/blob/master/filter.txt
https://github.com/annon79/Blockzilla/blob/master/Blockzilla.txt
https://github.com/AnXh3L0/blocklist/blob/master/personal.txt
https://github.com/anyuzu99/nothingblock/blob/main/filter.txt
https://github.com/arapurayil/aBL/blob/main/filters/nsfw.txt
https://github.com/arichr/bakadvert/blob/main/filters.txt
https://github.com/ATErBion/adblock-mylist/blob/master/lichost.txt
https://github.com/austinhuang0131/0131-block-list/blob/master/list.txt
https://github.com/Ayesh/Adblock-Sinhala/blob/master/filters.txt
https://github.com/B-Con/mute/blob/master/mute.txt
https://github.com/balupton/filters/blob/master/filter-activism.txt
https://github.com/banbendalao/ADgk/blob/master/kill-baidu-ad.txt
https://github.com/bbondy/abp-filter-parser/blob/master/test/data/easylist.txt
https://github.com/betterwebleon/international-list/blob/master/filters.txt
https://github.com/betterwebleon/slovenian-list/blob/master/filters.txt
https://github.com/bkazez/distractionblock/blob/master/distractionblock.txt
https://github.com/blocklistproject/Lists/blob/master/adguard/redirect-ags.txt
https://github.com/bmyjacks/adlists/blob/master/filter-registry/EasyPrivacy.txt
https://github.com/BPower0036/AdBlockFilters/blob/main/EasyDutch.txt
https://github.com/brave/adblock-lists/blob/master/coin-miners.txt
https://github.com/brawdevtest/ioG-list/blob/main/Filters/ioG.txt
https://github.com/bremich/Blocklists/blob/master/ublock/annoyances.txt
https://github.com/brunomiguel/antinonio/blob/master/antinonio.txt
https://github.com/byaka/ublock-antiskimming-list/blob/master/build/data.txt
https://github.com/caffeinewriter/DontPushMe/blob/master/filterlist.txt
https://github.com/Cinnamon-Unltd/Anti-Kpop-Spammers-Filterlist-for-Twitter/blob/main/AntiKPopSpammersFilterlistTwitter.txt
https://github.com/cjx82630/cjxlist/blob/master/cjx-annoyance.txt
https://github.com/cpeterso/clickbait-blocklist/blob/master/clickbait-blocklist.txt
https://github.com/Crystal-RainSlide/AdditionalFiltersCN/blob/master/RainSlide.txt
https://github.com/cxw620/AdGuard-Rules/blob/main/wjx-AdGuard.txt
https://github.com/Cybo1927/Hosts/blob/master/DNS%20Hosts
https://github.com/dagoll/filters-list/blob/master/dagoll-filters-list.txt
https://github.com/DandelionSprout/adfilt/blob/master/Anti-IMDB%20List.txt
https://github.com/DandelionSprout/Swedish-List-for-Adblock-Plus/blob/main/Swedish%20List%20for%20Adblock%20Plus.txt
https://github.com/DavidYaacov/adblock_youtube_paid/blob/master/youtube_paid_blocker.txt
https://github.com/DeepSpaceHarbor/Macedonian-adBlock-Filters/blob/master/Filters
https://github.com/durablenapkin/scamblocklist/blob/master/adguard.txt
https://github.com/EasyDutch-uBO/EasyDutch/blob/main/EasyDutch.txt
https://github.com/EasyList-Lithuania/easylist_lithuania/blob/master/easylistlithuania.txt
https://github.com/easylist-thailand/easylist-thailand/blob/master/subscription/easylist-thailand.txt
https://github.com/easylist/easylistchina/blob/master/easylistchina.txt
https://github.com/easylist/easylistdutch/blob/master/easylistdutch.txt
https://github.com/easylist/EasyListHebrew/blob/master/EasyListHebrew.txt
https://github.com/easylist/listear/blob/master/Liste_AR.txt
https://github.com/easylist/listefr/blob/master/liste_fr.txt
https://github.com/easylist/ruadlist/blob/master/advblock.txt
https://github.com/eEIi0A5L/adblock_filter/blob/master/ichigo_filter.txt
https://github.com/elypter/filter_processor/blob/master/sources/header.txt
https://github.com/elypter/generic_annoying_stickybar_filter/blob/master/generic_header_list.txt
https://github.com/endolith/clickbait/blob/master/clickbait.txt
https://github.com/ethanlevine/abp/blob/master/list.txt
https://github.com/evenxzero/Raajje-AdList/blob/master/filter.txt
https://github.com/examplecode/ad-rules-for-xbrowser/blob/master/core-rule-cn.txt
https://github.com/farrokhi/adblock-iran/blob/master/additional-trackers.txt
https://github.com/FiltersHeroes/KAD/blob/master/KAD.txt
https://github.com/FiltersHeroes/PolishAnnoyanceFilters/blob/master/PAF_newsletters.txt
https://github.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/blob/master/polish_rss_filters.txt
https://github.com/FiltersHeroes/PolishSocialCookiesFiltersDev/blob/master/adblock_social_filters/adblock_social_list.txt
https://github.com/finnish-easylist-addition/finnish-easylist-addition/blob/master/Finland_adb.txt
https://github.com/francis-zhao/quarklist/blob/master/dist/quarklist.txt
https://github.com/FutaGuard/LowTechFilter/blob/master/filter.txt
https://github.com/GamerGate/Adblock-Plus-filter-list/blob/master/GG-ABP.txt
https://github.com/gfmaster/adblock-korea-contrib/blob/master/filter.txt
https://github.com/gioxx/xfiles/blob/master/filtri.txt
https://github.com/gwarser/filter-lists/blob/master/my-filters.txt
https://github.com/Hackl0us/AdBlock-Rules-Mirror/blob/master/I-dont-care-about-cookies.txt
https://github.com/Hakame-kun/uBlock-Filters-Indonesia/blob/master/uBlock%20Indo/ubindo.txt
https://github.com/hant0508/uBlock-filters/blob/master/filters.txt
https://github.com/hawkeye116477/FilterListsDarkMode/blob/master/DarkFilterLists.txt
https://github.com/haykam821/Blocklists/blob/master/mmo.txt
https://github.com/hdd1013/AdBlockListSubKr/blob/master/filter.txt
https://github.com/HexxiumCreations/threat-list/blob/gh-pages/hexxiumthreatlist.txt
https://github.com/hit3shjain/Andromeda-ublock-list/blob/master/hosts.txt
https://github.com/hl2guide/All-in-One-Customized-Adblock-List/blob/master/aio.txt
https://github.com/hoshsadiq/adblock-nocoin-list/blob/master/nocoin.txt
https://github.com/hoshsadiq/blocked-hosts/blob/master/blocked-search-domains.txt
https://github.com/Hubird-au/Adversity/blob/master/Adversity.txt
https://github.com/hufilter/hufilter-dev/blob/master/sections/headers/adblock-plus.txt
https://github.com/hufilter/hufilter/blob/master/hufilter-abp.txt
https://github.com/HuzunluArtemis/TurkishAdblockList/blob/main/src/ElementalList.tx [...]

2022-08-01 14:33 UTC, scripthunter7 commented
@Alhadis
 
Firstly, we completely agree that a custom extension would be the _best_ solution for this situation. **But** the trouble is, it's a lot of work to rename these files, and in the beginning (perhaps for months or years) nothing would change because of this. Not to mention that the subscription url of the lists would change.

The "adblock agent" (`[Adblock Plus x.y]`, `[uBlock x.y]` /  `[uBlock Origin x.y]`,  `[AdGuard x.y]`, `[Adblock Plus x.y; AdGuard x.y]`) can be considered almost standard. If you look at the txt files linked in my previous comment, you can see that **most of them** start with this "agent". I think the remaining cases can be solved by opening issues or pull requests. **This can be clearly detected by heuristics.** What do you think about this opportunity? Considering the circumstances, this seems to me to be the _most optimal_ solution.

2022-08-01 22:01 UTC, scripthunter7 commented
I collected more links, manually. I also modified the heuristics so it only detects files that starts with the "adblock agent". I think false positive detection is 100% excluded, and the heuristics are also fast.

The heuristics:
https://github.com/scripthunter7/linguist/blob/0a2042081bf346ff5f0e85f5ea3f5ea98f5f117c/lib/linguist/heuristics.yml#L653-L655

File downloader (+ unique links):

<details>

<summary>Show script (contains 279 links)</summary>

```shell
wget "https://raw.githubusercontent.com/0ld/adblock-plus-2ch-ban/master/ban.txt"
wget "https://raw.githubusercontent.com/02030pllolipop/Rules-after-famlam-redundantRuleChecker/master/Big_mixtures_%26_breakdowns/A2.txt"
wget "https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt"
wget "https://raw.githubusercontent.com/acnapyx/paywall-remover/master/paywall-remover-anon.txt"
wget "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_112_ListeAR/filter.txt"
wget "https://raw.githubusercontent.com/andromedarabbit/List-KR/master/filter.txt"
wget "https://raw.githubusercontent.com/annon79/Blockzilla/master/Blockzilla.txt"
wget "https://raw.githubusercontent.com/AnXh3L0/blocklist/master/personal.txt"
wget "https://raw.githubusercontent.com/anyuzu99/nothingblock/main/filter.txt"
wget "https://raw.githubusercontent.com/arapurayil/aBL/main/filters/nsfw.txt"
wget "https://raw.githubusercontent.com/arichr/bakadvert/main/filters.txt"
wget "https://raw.githubusercontent.com/ATErBion/adblock-mylist/master/lichost.txt"
wget "https://raw.githubusercontent.com/austinhuang0131/0131-block-list/master/list.txt"
wget "https://raw.githubusercontent.com/Ayesh/Adblock-Sinhala/master/filters.txt"
wget "https://raw.githubusercontent.com/B-Con/mute/master/mute.txt"
wget "https://raw.githubusercontent.com/balupton/filters/master/filter-activism.txt"
wget "https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt"
wget "https://raw.githubusercontent.com/bbondy/abp-filter-parser/master/test/data/easylist.txt"
wget "https://raw.githubusercontent.com/betterwebleon/international-list/master/filters.txt"
wget "https://raw.githubusercontent.com/betterwebleon/slovenian-list/master/filters.txt"
wget "https://raw.githubusercontent.com/bkazez/distractionblock/master/distractionblock.txt"
wget "https://raw.githubusercontent.com/blocklistproject/Lists/master/adguard/redirect-ags.txt"
wget "https://raw.githubusercontent.com/bmyjacks/adlists/master/filter-registry/EasyPrivacy.txt"
wget "https://raw.githubusercontent.com/BPower0036/AdBlockFilters/main/EasyDutch.txt"
wget "https://raw.githubusercontent.com/brave/adblock-lists/master/coin-miners.txt"
wget "https://raw.githubusercontent.com/brawdevtest/ioG-list/main/Filters/ioG.txt"
wget "https://raw.githubusercontent.com/bremich/Blocklists/master/ublock/annoyances.txt"
wget "https://raw.githubusercontent.com/brunomiguel/antinonio/master/antinonio.txt"
wget "https://raw.githubusercontent.com/byaka/ublock-antiskimming-list/master/build/data.txt"
wget "https://raw.githubusercontent.com/caffeinewriter/DontPushMe/master/filterlist.txt"
wget "https://raw.githubusercontent.com/Cinnamon-Unltd/Anti-Kpop-Spammers-Filterlist-for-Twitter/main/AntiKPopSpammersFilterlistTwitter.txt"
wget "https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt"
wget "https://raw.githubusercontent.com/cpeterso/clickbait-blocklist/master/clickbait-blocklist.txt"
wget "https://raw.githubusercontent.com/Crystal-RainSlide/AdditionalFiltersCN/master/RainSlide.txt"
wget "https://raw.githubusercontent.com/cxw620/AdGuard-Rules/main/wjx-AdGuard.txt"
wget "https://raw.githubusercontent.com/dagoll/filters-list/master/dagoll-filters-list.txt"
wget "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Anti-IMDB%20List.txt"
wget "https://raw.githubusercontent.com/DandelionSprout/Swedish-List-for-Adblock-Plus/main/Swedish%20List%20for%20Adblock%20Plus.txt"
wget "https://raw.githubusercontent.com/DavidYaacov/adblock_youtube_paid/master/youtube_paid_blocker.txt"
wget "https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt"
wget "https://raw.githubusercontent.com/EasyDutch-uBO/EasyDutch/main/EasyDutch.txt"
wget "https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt"
wget "https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt"
wget "https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt"
wget "https://raw.githubusercontent.com/easylist/easylistdutch/master/easylistdutch.txt"
wget "https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt"
wget "https://raw.githubusercontent.com/easylist/listear/master/Liste_AR.txt"
wget "https://raw.githubusercontent.com/easylist/listefr/master/liste_fr.txt"
wget "https://raw.githubusercontent.com/easylist/ruadlist/master/advblock.txt"
wget "https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/ichigo_filter.txt"
wget "https://raw.githubusercontent.com/elypter/filter_processor/master/sources/header.txt"
wget "https://raw.githubusercontent.com/elypter/generic_annoying_stickybar_filter/master/generic_header_list.txt"
wget "https://raw.githubusercontent.com/endolith/clickbait/master/clickbait.txt"
wget "https://raw.githubusercontent.com/ethanlevine/abp/master/list.txt"
wget "https://raw.githubusercontent.com/evenxzero/Raajje-AdList/master/filter.txt"
wget "https://raw.githubusercontent.com/examplecode/ad-rules-for-xbrowser/master/core-rule-cn.txt"
wget "https://raw.githubusercontent.com/farrokhi/adblock-iran/master/additional-trackers.txt"
wget "https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt"
wget "https://raw.githubusercontent.com/FiltersHeroes/PolishAnnoyanceFilters/master/PAF_newsletters.txt"
wget "https://raw.githubusercontent.com/FiltersHeroes/PolishAntiAnnoyingSpecialSupplement/master/polish_rss_filters.txt"
wget "https://raw.githubusercontent.com/FiltersHeroes/PolishSocialCookiesFiltersDev/master/adblock_social_filters/adblock_social_list.txt"
wget "https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/master/Finland_adb.txt"
wget "https://raw.githubusercontent.com/francis-zhao/quarklist/master/dist/quarklist.txt"
wget "https://raw.githubusercontent.com/FutaGuard/LowTechFilter/master/filter.txt"
wget "https://raw.githubusercontent.com/GamerGate/Adblock-Plus-filter-list/master/GG-ABP.txt"
wget "https://raw.githubusercontent.com/gfmaster/adblock-korea-contrib/master/filter.txt"
wget "https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt"
wget "https://raw.githubusercontent.com/gwarser/filter-lists/master/my-filters.txt"
wget "https://raw.githubusercontent.com/Hackl0us/AdBlock-Rules-Mirror/master/I-dont-care-about-cookies.txt"
wget "https://raw.githubusercontent.com/Hakame-kun/uBlock-Filters-Indonesia/master/uBlock%20Indo/ubindo.txt"
wget "https://raw.githubusercontent.com/hant0508/uBlock-filters/master/filters.txt"
wget "https://raw.githubusercontent.com/hawkeye116477/FilterListsDarkMode/master/DarkFilterLists.txt"
wget "https://raw.githubusercontent.com/haykam821/Blocklists/master/mmo.txt"
wget "https://raw.githubusercontent.com/hdd1013/AdBlockListSubKr/master/filter.txt"
wget "https://raw.githubusercontent.com/HexxiumCreations/threat-list/gh-pages/hexxiumthreatlist.txt"
wget "https://raw.githubusercontent.com/hit3shjain/Andromeda-ublock-list/master/hosts.txt"
wget "https://raw.githubusercontent.com/hl2guide/All-in-One-Customized-Adblock-List/master/aio.txt"
wget "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt"
wget "https://raw.githubusercontent.com/hoshsadiq/blocked-hosts/master/blocked-search-domains.txt"
wget "https://raw.githubusercontent.com/Hubird-au/Adversity/master/Adversity.txt"
wget "https://raw.githubusercontent.com/hufilter/hufilter-dev/master/sections/headers/adblock-plus.txt"
wget "https://raw. [...]

2022-08-07 12:36 UTC, Alhadis approved these changes
@scripthunter7 I still need to download and go through the samples you've collected (thank you dearly for cutting out that step for me 😀), but I think we can get away with classifying only `.txt` files that match our heuristic; any other AdBlock filter files can be identified with a modeline and/or an [override](https://github.com/github/linguist/blob/02ffab2d4df3034c05fd7b2e8bf0a2fd31c0452d/docs/overrides.md):

**Modeline:**

~~~java-properties
! -*- adblock -*-
OR
! -*- vim:set ft=adblock:
~~~

**Override:**

~~~gitattributes
/path/to/filters.txt linguist-language=AdBlock
~~~

I've also cleaned the heuristic up a bit by culling redundant syntax and loosening the pattern to accept more than two version strings; i.e., so it matches stuff like `[AdBlock 1.0 ; uBlock 2.0  ; AdGuard 3.3]` (which I'm assuming is legal; correct me if my hunch is wrong).

~~~regexp
(?x)\A
\[
(?<version>
	(?:
		[Aa]d[Bb]lock
		(?:[ \t][Pp]lus)?
		|
		u[Bb]lock
		(?:[ \t][Oo]rigin)?
		|
		[Aa]d[Gg]uard
	)
	(?:[ \t] \d+(?:\.\d+)*+)?
)
(?:
	[ \t]?;[ \t]?
	\g<version>
)*+
\]
~~~

2022-08-31 14:42 UTC, Alhadis commented
@lildude This LGTM, from my own testing. 👍 You might have access to a larger corpora of `.txt` files with which to test the heuristic, though. 😉

2022-09-01 07:19 UTC, lildude approved these changes

2022-09-01 08:46 UTC, merged

2022-09-01 09:05 UTC, scripthunter7 commented
Thanks everyone for the tips and help! @Alhadis, thank you very much for your contribution! 🎉

2022-09-01 09:13 UTC, Alhadis commented
Nah mate, you did most of the heavy-lifting. 😉 If anything, we should be thanking you.

2022-09-05 19:11 UTC, krystian3w commented
https://github.com/DandelionSprout/adfilt/issues/63