Less greedy tokenization, fixes segfault
github/linguist pull request #5969
Opened 2022-07-10 18:48 UTC by smola

The tokenizer previously matched punctuation and symbols very greedily.
To do so, it required trailing contexts to differentiate from some types
of comments. This trailing context matching led to segfaults.

This commit changes the tokenizer to use less greedy matching of
symbols, and removes the need for trailing context. It has been tuned to
match most common operators, at least where it matters for
classification (checked with cross-validation).

Fixes #5938

## Description

## Checklist:

- [ ] **I am associating a language with a new file extension.**
  - [ ] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am adding a new language.**
  - [ ] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension:
      
      -  https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3AFOOBAR+KEYWORDS+NOT+nothack
  - [ ] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a syntax highlighting grammar: [URL to grammar repo]
  - [ ] I have updated the heuristics to distinguish my language from others using the same extension.

- [ ] **I am fixing a misclassified language**
  - [ ] I have included a new sample for the misclassified language:
    - Sample source(s):
      - [URL to each sample source, if applicable]
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

- [ ] **I am changing the source of a syntax highlighting grammar**
  - Old: [URL to grammar repo]
  - New: [URL to grammar repo]

- [ ] **I am updating a grammar submodule**
  

- [ ] **I am adding new or changing current functionality**
  
  - [ ] I have added or updated the tests for the new or changed functionality.

- [ ] **I am changing the color associated with a language**
  
  - [ ] I have obtained agreement from the wider language community on this color change.
    - [URL to public discussion]
    - [Optional: URL to official branding guidelines for the language]

2022-07-10 18:49 UTC, smola commented on script/cross-validation
> +ACCEPTABLE_ERRORS_ALL = 777
Note that the number of errors in master was 774 (it drifted, since it's not in CI). So the decrease in performance is not that bad.

2022-07-11 09:29 UTC, lildude requested changes
Thanks for this fix.

One request: can we add a test to catch this if there is a re-introduction in future. I'm not sure of the best way to do this, but I implemented a very crude test at https://github.com/github/linguist/pull/5956/files#diff-5a67ba96b8136be439db6c2234fd38f6395d6f898920c32e677b09263cb4fcc8R228-R241 which does the job which we could use here if there's no better way.

2022-07-12 13:15 UTC, lildude commented
I need to make the next release tomorrow at the latest so I'll pull in my test then if it's not been pulled in or a better alternative is provided.

2022-07-12 22:10 UTC, smola commented
@lildude I pulled your test, and also added one for a very long token (which segfauls on master).

2022-07-13 08:00 UTC, lildude approved these changes
Thanks @smola 🙇

2022-07-13 08:01 UTC, merged