docs: Add link to issue #5756
github/linguist pull request #6074
Opened 2022-09-15 16:41 UTC by detherminal

Added the link to issue #5756

2022-09-15 16:57 UTC, lildude approved these changes

2022-09-15 21:58 UTC, Alhadis requested changes

2022-09-15 21:58 UTC, Alhadis commented on CONTRIBUTING.md
> +(but see [#5756](https://github.com/github/linguist/issues/5756) for a temporary change in the criteria).
This link's been used twice, so I suggest keeping it DRY:

```suggestion
(but see [#5756][] for a temporary change in the criteria).
```

~~~diff 
 [grammars]: /vendor/README.md
 [heuristic]: https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml
 [languages]: /lib/linguist/languages.yml
 [licenses]: https://github.com/github/linguist/blob/9b1023ed5d308cb3363a882531dea1e272b59977/vendor/licenses/config.yml#L4-L15
 [new-issue]: https://github.com/github/linguist/issues/new
 [samples]: /samples
 [search-example]: https://github.com/search?utf8=%E2%9C%93&q=extension%3Aboot+NOT+nothack&type=Code&ref=searchresults
 [gpr]: https://docs.github.com/packages/using-github-packages-with-your-projects-ecosystem/configuring-rubygems-for-use-with-github-packages
+[#5756]: https://github.com/github/linguist/issues/5756
~~~

2022-09-15 21:59 UTC, Alhadis requested changes

2022-09-15 21:59 UTC, Alhadis commented on CONTRIBUTING.md
> +(but see [#5756](https://github.com/github/linguist/issues/5756) for a temporary change in the criteria).
As above:

```suggestion
(but see [#5756][] for a temporary change in the criteria).
```

2022-09-16 18:25 UTC, detherminal commented
@Alhadis Added it

2022-09-20 03:33 UTC, Alhadis requested changes

2022-09-20 03:33 UTC, Alhadis commented on CONTRIBUTING.md
> +(but see [#5756][5756] for a temporary change in the criteria).
```suggestion
(but see [#5756][] for a temporary change in the criteria).
```

2022-09-20 03:33 UTC, Alhadis commented on CONTRIBUTING.md
> +(but see [#5756][5756] for a temporary change in the criteria).
```suggestion
(but see [#5756][] for a temporary change in the criteria).
```

2022-09-20 03:33 UTC, Alhadis commented on CONTRIBUTING.md
> +[5756]: https://github.com/github/linguist/issues/5756
```suggestion
[#5756]: https://github.com/github/linguist/issues/5756
```

2022-09-20 20:57 UTC, Alhadis approved these changes

2022-09-20 22:04 UTC, merged