Add OASv2 and OASv3 languages
github/linguist pull request #6116
Opened 2022-10-14 00:01 UTC by whuji

## Description

Add OASv2 and OASv3 disambiguation as heuristics for JSON and YAML (see https://github.com/github/linguist/issues/6115)

## Checklist:

- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
  - [x] I have included a real-world usage sample for all extensions added in this PR
  - [ ] I have included a syntax highlighting grammar: no [^1]
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

[^1]: As an OAS can be either a JSON or a YAML file, I cannot add a syntax highlighting. I assumed that we want to count YAML OAS and JSON OAS together.

2022-10-17 09:47 UTC, lildude requested changes
See inline comments. 

The `ghes-3.4.*` samples are also massive. Please replace these with much smaller samples (ProTip: it the diff collapses them, they're too big 😉).

2022-10-17 09:47 UTC, lildude commented on lib/linguist/languages.yml
> +  type: programming
These are not programming languages, they're specifications written in JSON or YAML, which are both data types, so this should be `data` too. If a repo owner wants the name to appear in the language stats, they can implement an override.

```suggestion
  type: data
```

2022-10-17 09:47 UTC, lildude commented on lib/linguist/languages.yml
> +  type: programming
```suggestion
  type: data
```

2022-10-17 09:47 UTC, lildude commented on lib/linguist/languages.yml
> +  type: programming
```suggestion
  type: data
```

2022-10-17 09:47 UTC, lildude commented on lib/linguist/languages.yml
> +  type: programming
```suggestion
  type: data
```

2022-10-17 09:47 UTC, lildude commented on lib/linguist/languages.yml
> +  type: programming
```suggestion
  type: data
```

2022-10-17 09:47 UTC, lildude commented on lib/linguist/languages.yml
> +  type: programming
```suggestion
  type: data
```

2022-10-18 09:47 UTC, whuji commented
I have implemented all requested changes.
I know that OAS is data but I didn't know it was possible to configure GitHub to show that in languages card, that is why I set it to programming. In that regards, I didn't find how to override this setting, can you please guide me?

2022-10-18 09:50 UTC, lildude commented
> In that regards, I didn't find how to override this setting, can you please guide me?

https://github.com/github/linguist/blob/master/docs/overrides.md#detectable

2022-10-19 09:04 UTC, lildude submitted a review, later dismissed

2022-10-19 09:10 UTC, lildude requested changes
I've just noticed you've not added tests specifically for your new heuristics for matching the OAS files. Please add these.

2022-10-19 09:28 UTC, whuji commented
@lildude Yes, just added them + rebase from master for f-f merging.

Thanks !

2022-10-19 09:32 UTC, lildude approved these changes

2022-10-20 10:00 UTC, merged