Add .tres and .tscn to GDScript
github/linguist pull request #6185
Opened 2022-11-24 11:16 UTC by lildude

## Description

`.tres` and `.tscn` files form part of many GoDot aaps and are really popular on GitHub.

I've added them to GDScript as this is used for most GoDot files and GoDot's own documentation uses GDScript for syntax highlighting on their docs.

Fixes https://github.com/github/linguist/issues/6060

## Checklist:

- [x] **I am associating a language with a new file extension.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - [`.tscn`](https://github.com/search?q=path%3A*.tscn&type=code)
      - [`.tres`](https://github.com/search?q=path%3A*.tres&type=code)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/Orama-Interactive/Pixelorama
    - Sample license(s): MIT
  - [x] I have included a change to the heuristics to distinguish my language from others using the same extension.
    - Not needed as they're unique

2022-11-24 11:18 UTC, Alhadis approved these changes

2022-11-24 11:18 UTC, Alhadis commented on lib/linguist/languages.yml
> +  - ".tres"
You forgot `.uno`, `.dos` and `.cuatro`. 😉

2022-12-20 23:08 UTC, aaronfranke requested changes
This is completely and totally wrong.

* `.tres` and `.tscn` files are specific to Godot Engine, not to the GDScript language. Games using C# in Godot with no GDScript will still have `.tres` and `.tscn` files.

* The syntax highlighting needed for `.tres` and `.tscn` is completely different from GDScript.

2023-01-03 12:03 UTC, lildude commented
@aaronfranke I was kinda expecting a comment like this as I know nothing about Godot and was winging it 😁

> * `.tres` and `.tscn` files are specific to Godot Engine, not to the GDScript language. Games using C# in Godot with no GDScript will still have `.tres` and `.tscn` files.

The issue here is we can't add "Godot Engine" or similar as its own language to Linguist as it isn't a language, it's framework, hence I chose GDScript which brings me to your next point:

> * The syntax highlighting needed for `.tres` and `.tscn` is completely different from GDScript.

I was motivated to add these files to GDScript as that's what the [Godot docs](https://docs.godotengine.org/en/stable/development/file_formats/tscn.html) use for the code blocks (see the page source) and things seem to look OK. 

Now I'm looking at it again, and looking at the grammar itself, would it make more sense to add a new "GDResource" data language for these extensions? That's what VSCode identifies these file as when I open them with https://github.com/godotengine/godot-vscode-plugin/ installed (which we use for the GDScript syntax highlighting).

2023-01-03 21:05 UTC, aaronfranke commented
@lildude Yes, these files use Godot's Resource / ConfigFile format, including `project.godot`, `*.tres`, and `*.tscn`.

Note that we want to avoid marking these files as code (we should use Linguist `type: data`).

2023-01-09 11:28 UTC, Alhadis approved these changes
LGTM.

2023-01-09 21:59 UTC, aaronfranke commented on lib/linguist/languages.yml
> +  - project.godot
We can also add:

* Extension `".gdns"` (for GDNative)
* Extension `".gdnlib"` (for GDNative)
* Extension `".gdextension"` (for GDExtension)
* File name `override.cfg` (might be too generic of a name to put in Linguist, but we can determine if it's for Godot or not if it's next to `project.godot` in the file system, idk how to do this in Linguist).

2023-01-10 16:24 UTC, aaronfranke commented on lib/linguist/languages.yml
> +  - project.godot
Unfortunately there is nothing that will always appear in `override.cfg`, so yeah we can just leave it out.

2023-02-17 11:14 UTC, merged