Add Circom language support
github/linguist pull request #6204
Opened 2022-12-01 11:03 UTC by cryptopapi997

Added the Circom language

## Checklist:
- [x] **I am adding a new language.**
  - [x] The extension of the new language is used in hundreds of repositories on GitHub.com.
    - Search results for each extension: [>17k uses](https://github.com/search?utf8=%E2%9C%93&type=Code&ref=searchresults&q=extension%3Acircom)
  - [x] I have included a real-world usage sample for all extensions added in this PR:
      - [xor3, gpl3](https://github.com/iden3/circomlib/blob/master/circuits/sha256/xor3.circom)
      - [binsum, gpl3](https://github.com/iden3/circomlib/blob/master/circuits/binsum.circom)
      - [switcher, gpl3](https://github.com/iden3/circomlib/blob/master/circuits/switcher.circom)
    
  - [ ] I have included a syntax highlighting grammar: Only available grammar I could find was [this one by the developers of circom](https://github.com/iden3/circom-highlighting-vscode), but it is currently unlicensed.
  - [x] I have updated the heuristics to distinguish my language from others using the same extension.

2022-12-01 14:47 UTC, Alhadis commented
> It is GPL3, however

That's a deal-breaker. We only accept grammars released under [permissive licenses](https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/vendor/licenses/config.yml), which rules out copyleft licenses like GPL completely.

2022-12-02 06:50 UTC, Alhadis commented
> Can we still merge this PR without a grammar for now nonetheless?

Yes. You can even reappropriate another language's grammar if it happens to provide decent-enough highlighting.

2022-12-02 09:46 UTC, krlosMata commented
I will check other licenses that fits the requirements

2022-12-02 10:41 UTC, krlosMata commented
> > It is GPL3, however
> 
> That's a deal-breaker. We only accept grammars released under [permissive licenses](https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/vendor/licenses/config.yml), which rules out copyleft licenses like GPL completely.

I have change the license to MIT in https://github.com/iden3/circom-highlighting-vscode, so it fulfills the specification

2022-12-02 10:50 UTC, cryptopapi997 commented
Awesome! Currently out, but will add the grammar when I'm back :+1:

2022-12-08 04:46 UTC, cryptopapi997 commented
Added the circom grammar, feel free to have a look again @Alhadis

2022-12-12 11:18 UTC, lildude requested changes

2022-12-12 11:18 UTC, lildude commented on lib/linguist/languages.yml
> +  codemirror_mime_type: text/x-java
These don't seem right to me. The `codemirror` options are optional so if in doubt, remove and leave `ace_mode` as `text`:

```suggestion
  ace_mode: text
```

2022-12-12 11:18 UTC, lildude commented on lib/linguist/languages.yml
> +  tm_scope: none
This needs to be set to the scope in the grammar:

```suggestion
  tm_scope: source.circom
```

2022-12-12 11:36 UTC, cryptopapi997 commented
Thanks for the review, added your changes

2022-12-14 09:20 UTC, lildude approved these changes
LGTM. Thanks.

Note: this PR will not be merged until close to when the next release is made. See [here](https://github.com/github/linguist/blob/master/docs/troubleshooting.md#my-linguist-pr-has-been-merged-but-github-doesnt-reflect-my-changes) for more details.

2023-02-17 11:41 UTC, merged