Add `.slnx` to XML extensions
github/linguist pull request #7084
Opened 2024-10-09 15:49 UTC by kasperk81

## Description

## Checklist:

- [x] **I am adding a new extension to a language.**
  - [x] The new extension is used in hundreds of repositories on GitHub.com
    - Search results for each extension:
      
      - https://github.com/search?type=code&q=NOT+is%3Afork+path%3A*.slnx+solution
  - [x] I have included a real-world usage sample for all extensions added in this PR:
    - Sample source(s):
      - https://github.com/visose/Robots/blob/aa2be4ba40947b950b79d68fae3e22f32a0184c2/Robots.slnx
    - Sample license(s):
  - [ ] I have included a change to the heuristics to distinguish my language from others using the same extension.

Fix https://github.com/github-linguist/linguist/issues/7083

2024-10-09 16:40 UTC, rainersigwald reviewed
Ah yeah, getting the default XML highlighting is a great low-cost way to do this!

2024-10-14 16:35 UTC, lildude requested changes
Your sample should be in the `samples/XML` directory.

2024-10-14 16:54 UTC, lildude commented
> @lildude ok, but can you tell me why?

Sure... it's what you want 😉 

![Screenshot 2024-10-14 at 17 52 58](https://github.com/user-attachments/assets/ca0e86e8-28c4-4131-8d03-84ea8b68c5d1)

As you're adding the extension to the XML language entry, you're saying these files are XML and should be highlighted as XML and as such, the sample needs to go into the XML language directory.

2024-10-14 17:26 UTC, lildude commented
You need to add this to the list of no-root-tag entries in the test too:

https://github.com/github-linguist/linguist/blob/f164d13fa618023ecf2d8f2ed9a6ce5fae731346/test/test_strategies.rb#L176-L194

This will exclude the sample from the XML strategy testing which is what is failing here.

2025-02-27 08:32 UTC, lildude commented
> Hello @lildude just wondering if you and your team had had the chance of taking a look into this.

No. I only review pending popularity PRs when I make a new release which happens approximately every 3-4 months.

2025-06-02 09:19 UTC, merged